### ISSUE TITLE
API for check license method

### ISSUE THREAD

**Issue by rtgdk** [spdx/spdx-online-tools#10]
Implement an api for check license method. Take a file as an input, parse it to send the text as a parameter to the spdx java tool function.

To implement the api, take inspiration from [here ](https://github.com/spdx/spdx-online-tools/blob/24745d8ab0a3b46830c378202044276c1b414a91/src/app/views.py#L694)and [here](https://github.com/spdx/spdx-online-tools/blob/24745d8ab0a3b46830c378202044276c1b414a91/src/api/views.py#L55)

**Comment by susg** [comment]
I would like to work on this issue.

**Comment by rtgdk** [comment]
You are welcome to do so. Ping me if you face any problem.

**Comment by susg** [comment]
yeah, sure.

**Comment by yugeshk** [comment]
Contrary to the App style, the API would probably require a text file for license. So should the API call save the file it receives?

**Comment by yugeshk** [comment]
Oh sorry. Didn't see another PR for the same. :sweat:

**Comment by rtgdk** [comment]
@yugeshk  Yes. We would like to save the file for now.
