### ISSUE TITLE
license submit: instructions for fields/form

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-online-tools#106]
is it possible to add some instructions at the top of the page?

similarly, could we add hints for how to fill out some of the fields - maybe via a popup or via some text in the field that disappears when you then start typing?

**Comment by techytushar** [comment]
IMO, before each input field we can add a small :question: icon, hovering on which, will display more info about that field.

**Comment by goneall** [comment]
Documentation for the different fields can be found at https://spdx.org/spdx-license-list/license-list-overview

**Comment by goneall** [comment]
We could/should add a[ link to the overview](https://spdx.org/spdx-license-list/license-list-overview) page to provide the detailed information on the license list.

**Comment by jlovejoy** [comment]
@techytushar I like the small ? icon idea, which you then hover over to display more text.
@goneall - I'd skip adding a link to the overview page for now. we are in the midst of a re-write. 
but some instructions at the top - maybe a sentence or two would be good. (In my experience, when you have a ? icon with hover-over text, you have to actually tell people that it's there :)

**Comment by goneall** [comment]
@jlovejoy sounds good - let's skip the link to the overview and just add a couple sentences.  To you have any text in mind?  If you can add it as a comment, that would be quite helpful.

**Comment by Ugtan** [comment]
@goneall @jlovejoy @teckytushar I would like to work on the issue.

**Comment by goneall** [comment]
@Ugtan Sounds good.  You can take the text from the field descriptions in the link above.  

@jlovejoy Let us know if you think any of the field descriptions will change.  Perhaps you can review the PR before merging.

**Comment by jlovejoy** [comment]
@goneall , @Ugtan - for the pop-up text for the fields, as per @techytushar 's suggestion, please use the following from https://spdx.org/spdx-license-list/license-list-overview#fields or notes below in "quotes":

License's Full Name = use bullets at A) Full Name on the above page
Short Identifier = use bullets at B) Short Identifier
Source / URL = use bullets at C) Other web pages for license/exception
Standard License Header= use bullets at H) Standard License Header
License Text = "full license of the license text"
Comments = "Provide a short explanation regarding the need for this license or exception to be included on the SPDX License List, and identify at least one program that uses it or any other related information."

I think the remaining fields don't need any explanatory text.

Hopefully that all makes sense!

**Comment by Ugtan** [comment]
@jlovejoy @techytushar @goneall @rtgdk I have added a PR regarding the issue and would like your feedback on the same. Please have a look at it. Thank you.

**Comment by goneall** [comment]
@Ugtan Looks good.  The text looks a little long for hover over, but it does contain a lot of information.

**Comment by Ugtan** [comment]
@goneall Exactly. That is why i used bootstrap popover instead of tooltip as they look fine with a lot of info as well. Although, i can remove the hover over if you want then, it will act as a simple popover.

**Comment by goneall** [comment]
> Although, i can remove the hover over if you want then, it will act as a simple popover.

I like the way it works.  It would be great to get @jlovejoy 's feedback on the look and feel, but we would need to deploy it first.  I"m thinking we go ahead and merge, deploy and if we want to do any fine-tuning, we create a separate PR.

@techytushar Does this look good to you?  If so, I'll go ahead and merge.

**Comment by Ugtan** [comment]
> I"m thinking we go ahead and merge, deploy and if we want to do any fine-tuning, we create a separate PR.

Sounds good to me @goneall

**Comment by goneall** [comment]
I'm going to re-open this issue until @jlovejoy Jilayne has a chance to review the implementation.

@jlovejoy The tooltip code has been deployed to spdxtools.sourceauditor.com

**Comment by jlovejoy** [comment]
this looks good!  Do you think we need a sentence at the top of the page saying something like: 
"Please follow the guidance in the pop-up for the fields to ensure all the correct information is provided."
Or is it obvious enough that one should read the info in the ? pop-up, do you think?

**Comment by goneall** [comment]
I'm leaning towards no sentence, but I just went through and looked at the pop-ups - we could probably validate most of the items and give an error if they don't follow the naming rules.  I'll open a separate issue to track.

**Comment by jlovejoy** [comment]
sounds good to me!

**Comment by goneall** [comment]
Closing this issue - created issue #115 to track validating fields.
