### ISSUE TITLE
Archive button only visible to logged in users

### ISSUE THREAD

**Issue by techytushar** [spdx/spdx-online-tools#107]
Currently the Archive button on the `license_requests/` page and Unarchive button on the `archive_requests/` page is visible to everyone, so anyone can just press the buttons and mess things up. These buttons should only be visible to the users who are logged in. What do you think @goneall

**Comment by Ugtan** [comment]
I feel like the archive feature should be  available only on those licenses which are created by the user while the members of the SPDX legal team should have the access to archive any license which are important but can be delayed for a while. Also, we could have a different section or something for the new license requests in the online tools. So, that legal team can decide on the basis of the priority of this new submitted license either to put it on the priority list or archive the license for now. Not sure if its a good idea, would like to have your feedback. @techytushar @goneall

**Comment by goneall** [comment]
@techytushar I agree with the issue.  Since we can always unarchive, at least we can undo any damage.

@Ugtan I like your proposal.  The only issue is determining who are members of the legal team.  We could use the list of users with write access to the license-list-XML repository.  I don't know how easy it would be to use the Github API to check this, but it would be the simplest UI.  Another approach would be to have certain users with admin access and somehow keep track of this.  It may require another UI if we take the latter approach.

**Comment by Ugtan** [comment]
An approach could be we could create a new [organisation](https://help.github.com/en/enterprise/2.16/admin/user-management/creating-organizations) something like `spdx legal team` and using the github api find the members of this organisation and give them permission to access the archive feature. I am not sure if it will be a efficient method. Also, i am unsure if its possible, will try to do some more research on this. @goneall

**Comment by rtgdk** [comment]
@techytushar @goneall @Ugtan  We can also set the `ANONYMOUS_LOGIN_ENABLED = false` from setting.py or use some other variable for `license_request.html` page. All the legal team can use one single login(shared only among the legal team). We can restrict access to archiving/unarchiving `license_request.html` to this single user and also provide the license submitter with the same access, if needed.

**Comment by goneall** [comment]
@rtgdk I like the convenience of using github for the login.

@Ugtan It looks like we already have an organization "spdx" which is a superset of the legal team.  I actually think this is close enough.  If there is an API which let's us check of a user is a member of the spdx organization, I think that approach would work.

@jlovejoy Let me know if you agree

**Comment by jlovejoy** [comment]
I think that all sounds good

**Comment by anshuldutt21** [comment]
Is this issue still open? As far as I can understand we want that the archive features are available to the legal spdx team and to the user who created them. right?

**Comment by rtgdk** [comment]
@anshuldutt21 yeah, right. you are welcome to suggest any ideas on how to get this permission only for the legal spdx team (like you have a list of spdx legal team users) and the user who created it.
As @goneall  said above

> The only issue is determining who are members of the legal team. We could use the list of users with write access to the license-list-XML repository. I don't know how easy it would be to use the Github API to check this, but it would be the simplest UI. Another approach would be to have certain users with admin access and somehow keep track of this. It may require another UI if we take the latter approach

You can suggest any other approach you can think of and raise a PR for the same.
