### ISSUE TITLE
Add listVersionAdded="" tag to license tag

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#108]
When creating the license XML for a newly submitted license, add the attribute `listVersionAdded ` with a default value of empty string (e.g. `<License isOsiApproved="false" licenseId="newlicense" name="newLicense" listVersionAdded="">`

This would make it easier to add the list version once a license has been approved.

This issue has been split off from issue #100

**Comment by goneall** [comment]
We could also automate the insertion of the listVersionAdded in the Travis continuous build script on release if it is still empty.

If we want to automatically check or update this field, we should add a separate issue for the Travis tools update.

**Comment by Ugtan** [comment]
I would like to work on the issue. @goneall

**Comment by goneall** [comment]
@Ugtan Go ahead and work on the issue.  Thanks.

**Comment by Ugtan** [comment]
@goneall I have added a PR to fix the issue. Please have a look at it. Thanks.

**Comment by goneall** [comment]
@Ugtan PR looks good.  Once @rtgdk merges, we can close the issue.

Thanks!

**Comment by Ugtan** [comment]
> @Ugtan PR looks good. Once @rtgdk merges, we can close the issue.

Sounds good to me 😊
