### ISSUE TITLE
Validate license submittal fields

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#115]
This license name and license ID can be validated using the rules documented in the pop over text.  We can pick a max. length of a short identifier - perhaps 25 characters.  We can make sure all characters are valid.

For the license name, we can check for starting with "the", parenthesis, etc.

Check the pop over text for what can be validated.

This is related to issue #106

**Comment by Ugtan** [comment]
@goneall I would like to work on the issue.

**Comment by goneall** [comment]
@Ugtan That would be great.  Thanks,
