### ISSUE TITLE
add links to fields in license submittal form

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-online-tools#117]
can someone update the text in the license submittal form pop-up to reflect the addition of the links as is shown here https://github.com/spdx/license-list-XML/pull/862
(assuming links are an option in the pop-up text)

**Comment by jlovejoy** [comment]
can we also fix the header so it says, "Submit a new license to the SPDX License List" 
(not "Licenses List" :)

thanks!

**Comment by rtgdk** [comment]
Changes merged with https://github.com/spdx/spdx-online-tools/pull/146
