### ISSUE TITLE
Change from creating a PR to creating an issue when there is a close match in a license submittal

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#135]
PR #128 implements a feature where if there is a close match, the user can submit a pull request to update the XML to allow for the match.

After trying this out on my local machine, it occurred to me that many users may not have the technical skills or interest in creating the XML with the proper `<optional` or `<alt...` tags.  We could instead create an issue with a title "Update [licenseID] to allow matching to the included text".  The text of the license and/or the diff could added as a comment or as an attachment to the issue.

@jlovejoy @swinslow - let me know what you think.

**Comment by swinslow** [comment]
Sounds great to me :)
