### ISSUE TITLE
Create a Docker Image

### ISSUE THREAD

**Issue by techytushar** [spdx/spdx-online-tools#14]
It would be great if there is a Dockerfile and the user can just build a Docker image and use the platform locally.

**Comment by rtgdk** [comment]
Well for using the platform locally, there is already the [java tools](https://github.com/spdx/tools/) providing many more functionality. I don't see any point of using the "online" tools locally. Moreover, we have already built an API so the user won't even need to install anything.

**Comment by techytushar** [comment]
fully agree, my bad :sweat_smile: , should i close this then?

**Comment by rtgdk** [comment]
Done.
