### ISSUE TITLE
Update git authentication method

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#142]
Email from github:

On February 7th, 2020 at 21:47 (UTC) your application (SPDX Online Tools) used an access token (with the User-Agent python-requests/2.20.1) as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

**Comment by anshuldutt21** [comment]
@goneall Do we need to completely remove the github authentication and replace it with the oauth authentication or authorization headers.

**Comment by goneall** [comment]
> Do we need to completely remove the github authentication and replace it with the oauth authentication or authorization headers.

That is my understanding from reading the github documentation at https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

**Comment by goneall** [comment]
@anshuldutt21 Did you get a chance to look into this issue?  @rtgdk do you know which features will be impacted by this?  I haven't gotten any emails recently from Github, so I'm not sure if this is still an issue.

**Comment by anshuldutt21** [comment]
@goneall No, I couldn't find a good alternative for the access token. Is there any problem with the authentication currently since in the mail it said access token parameter will be removed by July 1st.

**Comment by rtgdk** [comment]
@anshuldutt21 @goneall The issue is with passing "access_token" in query url as parameter(?access_token=<token>)...instead we should pass it through the api headers. In the email, the api mentioned is "https://api.github.com/user" which is only used in testing `test_submitlicense_api_with_valid_fields` in `api/tests.py` which passes the token correctly (in headers). I am not sure why we got this error on Feb 7th and not later on since this test used headers from the beginning. @Ugtan Do you remember if you used this api with access token as params?

**Comment by Ugtan** [comment]
@rtgdk Correct. The only place we used the user api is in `test_submitlicense_api_with_valid_fields`. I don't think we have used `access_token` as a query string anywhere else in the codebase.

I'm not quite sure but I think one of the libraries we are using uses the `access_token` as a query parameter. It could be `social-auth-app-django` but I'm not sure. We can update the libraries to check if everything works fine. Also, I just notice that the deadline for deprecation is extended until May 2021 from the [article](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/).

**Comment by goneall** [comment]
Good news on the deadline being moved out to May 2021 (thanks @Ugtan for the research).  It would still be nice to close on this, so perhaps we can update the libraries.

**Comment by goneall** [comment]
I started getting the emails again about this being deprecated.

I found this issue in `social-auth-app-django` : https://github.com/python-social-auth/social-core/issues/430

which was fixed in PR https://github.com/python-social-auth/social-core/pull/428

which is in version 3.4.0.

We're current at version 2.1.0.

It looks like updating to version 3.4.0 should resolve this.

**Comment by rtgdk** [comment]
PLease reopen if we get that email again.
