### ISSUE TITLE
Running the server shows an error no module named secret in settings.py file

### ISSUE THREAD

**Issue by anshuldutt21** [spdx/spdx-online-tools#144]
While running the command python manage.py runserver an error comes up showing no module exists named secret in settings.py file. It should be renamed as
from .secret import getgithubkey and others,  since we are accessing the file in the same directory as of the settings.py file

**Comment by rtgdk** [comment]
@anshuldutt21 Are you sure this is not specific to the python version/ virtualenv setup / Django version? because it has beem working fine for us in the past.

Did you setup your local repo using the instruction in README?

**Comment by anshuldutt21** [comment]
@rtgdk I think you are right about this issue being specific to the python version. I tried resetting up and it worked.

**Comment by rtgdk** [comment]
Closing this then.
