### ISSUE TITLE
Add command python manage.py makemigrations in the documentation

### ISSUE THREAD

**Issue by anshuldutt21** [spdx/spdx-online-tools#147]
We should add the command python src/manage.py makemigrations in the docs since the migrations for app doesnt work unless we do makemigrations for it.

**Comment by rtgdk** [comment]
@anshuldutt21  Are you sure about this? Because migrations are already added in the migrations folder. If you still had to run makemigrations look at the diff when the command is run, if it creates some new file please open a PR for the same. 
Also, another way is to remove the folder and then run the command, this will create only one file `0001_initial.py` and then you can find the diff.

The idea is to minimize the no. of commands user needs to run for setting up the project.

**Comment by anshuldutt21** [comment]
@rtgdk yes it does create a new file in the migrations after runninig the command.

**Comment by rtgdk** [comment]
@anshuldutt21 Can you paste the content of it?

**Comment by anshuldutt21** [comment]
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseAuthorName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fullname', models.CharField(max_length=70)),
                ('shortIdentifier', models.CharField(max_length=25)),
                ('submissionDatetime', models.DateTimeField(auto_now_add=True)),
                ('userEmail', models.EmailField(max_length=35)),
                ('notes', models.CharField(default='', max_length=255)),
                ('xml', models.TextField()),
                ('archive', models.BooleanField(default=False)),
                ('publiclyShared', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('namespace', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('license_list_url', models.URLField(max_length=250)),
                ('github_repo_url', models.URLField(max_length=250)),
                ('promoted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'LicenseNamespace',
                'verbose_name_plural': 'LicenseNamespaces',
            },
        ),
        migrations.CreateModel(
            name='OrganisationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('orgId', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'OrganisationName',
                'verbose_name_plural': 'OrganisationNames',
            },
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='licenseAuthorName',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='licensenamespace',
            name='license_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.LicenseRequest'),
        ),
        migrations.AddField(
            model_name='licensenamespace',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.OrganisationName'),
        ),
    ]

**Comment by anshuldutt21** [comment]
The above file is the 2nd migration file created after doing makemigrations. The contents are also different. I think the best way should be to run makemigrations in the docs before migrating.

**Comment by rtgdk** [comment]
@anshuldutt21 Okay, I got it. These models were created last year and the changes haven't been migrated in the migrations files.
Can you raise a PR, after deleting the migrations folder rerun the migrations command which will append changes to `0001_initial.py` ? (We want only one file in migrations folder)
We don't want any developer/user to run makemigrations (one less command to setup the repo), so we provide premigrated files in the repo.
