### ISSUE TITLE
Submit new license request doesnt work since License Request is not imported

### ISSUE THREAD

**Issue by anshuldutt21** [spdx/spdx-online-tools#148]
We need to import the License Request from the models to make it work

**Comment by rtgdk** [comment]
Can you post the error? @anshuldutt21

**Comment by anshuldutt21** [comment]
![Screenshot from 2020-02-15 21-46-29](https://user-images.githubusercontent.com/45336622/74591301-d4ff9180-503c-11ea-86c8-cd1f90332a18.png)
This is the error that appears when we submit a new license request.

**Comment by rtgdk** [comment]
@anshuldutt21 But it works in production, can you please check your local setup/ virtualenv? I think this is a python import error specific to the version.

Also, did you try and replicate this in production? https://spdxtools.sourceauditor.com/

**Comment by anshuldutt21** [comment]
@rtgdk It works in production. But I dont understand how it is working if we have'nt imported the model License Request in utils.py. The name will remain undefined. Also I  think there won't be any harm in adding a word along with from app.models import User, UserId. It will make it less prone to version specific errors.

**Comment by rtgdk** [comment]
@anshuldutt21 If you think it's a real issue, you can raise a PR and we will check that on our end.

**Comment by techytushar** [comment]
Closing this, resolved in #149
