### ISSUE TITLE
Display loading bar when a process is running

### ISSUE THREAD

**Issue by techytushar** [spdx/spdx-online-tools#15]
It would be great if there is a loading bar displayed when a process is running and even better if we can show the progress also.

**Comment by rtgdk** [comment]
That's a nice idea. But how would we get, how much % of work has been done by the java tools to process the file. If you intend to display, just a random process bar we can workout how much time it usually takes to process file(s) in validation/conversion/comparison and according to that, we can display a more relevant process bar. 
Also, in comparison of multiple files, we can modify the java tool to give us some signal through JPype when it has finished processing some file to display, "File 1 finished processing" or something equivalent on the process bar.
The whole idea of process bar is good, but other changes have higher priority. This can be included to the Todo-Gsoc-work once the main work is finished properly.

**Comment by jlovejoy** [comment]
I don't think this is critical and considering how old it is, I'm going to close.
