### ISSUE TITLE
Innovative popover while submitting license 

### ISSUE THREAD

**Issue by rtgdk** [spdx/spdx-online-tools#151]
The current popover in the Submit License page cannot handle scrolling, also it doesn't support mouse click. User has the keep mouse hover over the element to see the info.

It would be more intuitive to have a proper hover over which can open with a click and does not close until another click happens on other part of screen. It should also support scrolling since the text in the info popover is too large.

Any other innovative idea to show these info is welcomed.

**Comment by ekongobie** [comment]
@rtgdk Can I work on this?

**Comment by rtgdk** [comment]
@ekongobie Sure.

**Comment by jlovejoy** [comment]
@rtgdk - looks like we can close this?

**Comment by jlovejoy** [comment]
I'm closing this as we have removed pop-ups on the Submit License tool due to the pop-ups not being accessibility friendly.
