### ISSUE TITLE
non-existent mail address is shown

### ISSUE THREAD

**Issue by felijung** [spdx/spdx-online-tools#158]
When using the SPDX Online Tool without being signed in to GitHub, a dialogue appears which also gives the mail address spdx-legal@spdx.org. Mails to this address do not get delivered. Screenshot of dialogue attached.
![spdx-mail](https://user-images.githubusercontent.com/59148463/81273035-992e0400-904e-11ea-81cb-490d40b219ec.png)

**Comment by goneall** [comment]
The correct email is spdx-legal@lists.spdx.org
