### ISSUE TITLE
GSoC image in the README.md file.

### ISSUE THREAD

**Issue by Yash-Varshney** [spdx/spdx-online-tools#160]
**SUMMARY**

The first pic under README.md when we open [spdx-online-tools](https://github.com/spdx/spdx-online-tools/issues/new) seems to be of GSoC. Instead of this,` spdx-online-tools` logo should be used ( if there is one), or else it should be updated with a more desired title image.

**Comment by rtgdk** [comment]
@Yash-Varshney Makes sense. It should be a combined logo of SPDX and GSoC. Since GSoC made this project possible, we have to give it credit.

**Comment by Yash-Varshney** [comment]
@rtgdk thanks for briefing. I will make a PR changing it to a combined image, if its ok?
Also, `spdx-online-tools` is a project in `community bridge` program. Can you suggest me something to work to increase my chances with that ?
Thanks

**Comment by rtgdk** [comment]
@Yash-Varshney I would recommend you to get involved in spdx community, go through the repos, find new issues, and fix existing issues.
Find all the repos here: https://github.com/spdx
Pick up any issue which you feel you can do in any repository and raise a PR.

**Comment by Yash-Varshney** [comment]
@rtgdk I believe the purpose of this issue is finished! I am closing the issue..
