### ISSUE TITLE
ImportError: No module named 'secret'

### ISSUE THREAD

**Issue by kmehant** [spdx/spdx-online-tools#162]
The `secrets` module was added to Python in version 3.6. So shall we add this compatibility point to the README.md so that a version 3.6 or higher would be used?

**Comment by kmehant** [comment]
@goneall @rtgdk  Shall we add this to the README.md?

**Comment by shubhamgupta2956** [comment]
@goneall @rtgdk Apart from using the Python 3.6+ version, we have to change the location of `secret.py` file from `src/src/secret.py` to `src/secret.py` as that was the location specified in the `settings.py` file. Alternatively, we can change the location of `secret.py` file in `settings.py` file also.

**Comment by rtgdk** [comment]
The master is built with python2 and Django=1.11.18, you should have not faced this error while setting up the repo. The fix for this should be deployed either in the branch python3 (where we track python3 upgrade) for #58  #24

**Comment by shubhamgupta2956** [comment]
Hi @rtgdk. I went through the python3 branch. It has the last commit merged around Dec 2018. Since this file was not created at that time, it was not there. Same for #164. Should I add this file and modify it accordingly to solve #142 as well or just add this file there and add two different PRs solving both issues separately?

**Comment by rtgdk** [comment]
@shubhamgupta2956 Add 2 different PRs. Btw, I want to know whether you were able to setup the repo with python2 and secret file worked fine? (no import error, right?)
You can raise a separate PR for implementing secret.py for python3. 
Python3 branch was cut before last year's projects. One of the pending major task is to migrate to python3 - which can be a side project for Community Bridge program.

**Comment by shubhamgupta2956** [comment]
Yes, I had setup the repo using python2 and it is working fine. I will try to make PR for it ASAP.
