### ISSUE TITLE
Maintiain Credentails using environment variables

### ISSUE THREAD

**Issue by kmehant** [spdx/spdx-online-tools#181]
This model of maintaining sensitive data will be beneficial for

secure testing in Travis (by using Travis environment variables)
container-based setup (passing environment variables to containers would maintain our sensitive data without having them part of the actual code)
Easier and cleaner for local setup (as they maintain their own .env file so there will be no need to worry about committing the code with credentials)

**Comment by rtgdk** [comment]
Similar to #85

**Comment by goneall** [comment]
Resolved with PR #180
