### ISSUE TITLE
Add a License Diff section to the SPDX Online Tools

### ISSUE THREAD

**Issue by Ugtan** [spdx/spdx-online-tools#186]
We can add a new section to the Online tools which will take license text from the user and shows diff if the license entered by the user is a close match. That way we could inform the user beforehand that a license that closely matches the license user has entered is already present on the SPDX License List. Alternatively, we can improve the check license functionality to display license IDs for perfect matches and display diff in case of close matches. Currently the only way to check for close matches is if the user submits the license request and then, a pop up generates.

**Comment by Ugtan** [comment]
@goneall @rtgdk Let me know your thoughts on the issue.

**Comment by goneall** [comment]
Sounds like a useful feature.  There is a Chrome and Firefox plugin for license diff: https://github.com/spdx/spdx-license-diff  

Note: If we were to use the code from this plugin, we would need to change the license to GPL-3.0 to be compatible.

**Comment by rtgdk** [comment]
@Ugtan Sounds good. But we need to decide where to show this feature - should we provide a button next to xml text field in submit license? Or create a new view, or alter the check license view? Displaying license IDs and diff is a great idea.

**Comment by Ugtan** [comment]
> Note: If we were to use the code from this plugin, we would need to change the license to GPL-3.0 to be compatible.

I spent some time looking at the code of the license diff. I personally feel we will have to make quite a few changes to the code base to make it work for our use case. Also, I think we should not mess the plugin IMO. A better and easier way here would be to use https://github.com/spdx/spdx-online-tools/blob/4c08565b8511a63196537b953c7f7d6b588e42e8/src/app/utils.py#L479 Since, we already maintaining redis for SPDX License list it would be easy to get all the matching IDs and apply Levenshtein distance and generate diff. @goneall 

> But we need to decide where to show this feature - should we provide a button next to xml text field in submit license? Or create a new view, or alter the check license view? 

IMO it would be better to have a different section and thus, a new view. what do you think? @rtgdk

**Comment by rtgdk** [comment]
@Ugtan New view makes sense but then we already have a view for check licenses. Also, making this as api will be better so that we can show the user a button on the submit license page under xml field to check the license diff.

**Comment by Ugtan** [comment]
> New view makes sense but then we already have a view for check licenses. Also, making this as api will be better so that we can show the user a button on the submit license page under xml field to check the license diff.

I agree. Api to check the license diff and a button on the submit license page works well too.

**Comment by rtgdk** [comment]
Yes was completed with https://github.com/spdx/spdx-online-tools/pull/345/.
