### ISSUE TITLE
Add HTTPS support for Spdx Online Tools

### ISSUE THREAD

**Issue by Ugtan** [spdx/spdx-online-tools#189]
So far, we only support deploying over HTTP. We should consider adding support over HTTPS of Spdx Online tools. I would recommend using [certbot](https://certbot.eff.org/) for the same.

**Comment by Ugtan** [comment]
What are your thoughts on this? @goneall @rtgdk

**Comment by goneall** [comment]
@Ugtan Definitely a high priority.

I'm going to setup a new github account just for the online tools.  Once that is setup we can get the certs and set this up.

**Comment by Ugtan** [comment]
Sounds good @goneall

**Comment by goneall** [comment]
I found 2 docker configurations for SSL using nginx:

1. https://medium.com/faun/setting-up-ssl-certificates-for-nginx-in-docker-environ-e7eec5ebb418
2. https://testdriven.io/blog/django-lets-encrypt/

I'm leaning to the 1 as it is simpler and (I think) we can preserve the redirect to production.

We can use either certbot or let-encrypt.

@swinslow @rtgdk @Ugtan @kmehant Any thoughts?

**Comment by rtgdk** [comment]
Let's go with `certbot`. I think certbot itself is a wrapper over `lets-encrypt`

**Comment by goneall** [comment]
I added PR #219 to resolve this issue

**Comment by goneall** [comment]
Resolved in PR #258
