### ISSUE TITLE
Use an environment variable for the redis host

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#193]
The localhost can not be used for redis in the current container environment.  Creating an environment variable would allow the redis host to be configured outside the source.

If no environment variable is present, we could default it to the current `localhost` for compatibility.

See the containerize pull request #188 for a discussion on the topic.

**Comment by goneall** [comment]
The same environment variable should be used for both the spdx-license-matcher and the spdx-online-tools.  

Suggest `SPDX_RDIS_HOST`.

See the related issue https://github.com/spdx/spdx-license-matcher/issues/3

**Comment by kmehant** [comment]
Shall I take up this 😁

**Comment by goneall** [comment]
@kmehant Please do go ahead - thanks!

**Comment by kmehant** [comment]
@goneall 
Fixed at https://github.com/spdx/spdx-license-matcher/pull/4 and https://github.com/spdx/spdx-online-tools/pull/203
