### ISSUE TITLE
Decide on deployment Google Cloud or Amazon AWS

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#194]
The current online tools is deployed on an Amazon AWS EC2 server.

As we move to a more container based deployment, we need to choose whether to stay on AWS and utilize EKS and RDS or if we should move to Google Cloud with GKE and Google Cloud SQL.

**Comment by goneall** [comment]
I would like to decide on this by July 27th so I can setup a sandbox environment running our current container definitions.

My current thinking is to use AWS, primarily because I a more familiar with the AWS services relative to Google.

@kmehant @Ugtan @rtgdk Let me know if you have any thoughts or preference.

**Comment by kmehant** [comment]
Dealing with the production deployment, it will be good to go with the most familiar services so **+1 to AWS**

**Comment by rtgdk** [comment]
@goneall Let's go ahead with **AWS** since they have the most active community and even if we face some issues, most probably the solution would be available on SO.

**Comment by goneall** [comment]
AWS it is - I setup a separate account for the SPDX online tools.  I'll setup an RDS database next week and we can try a staging area with a deployed docker image.

**Comment by goneall** [comment]
Resolved as a decision to use AWS.
