### ISSUE TITLE
New deployment architecture

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#198]
This issue is to track a discussion on the new deployment architecture.

The current proposal is to have a Kubernetes managed container based architecture with a separate managed database server.

**Comment by goneall** [comment]
Based on the information Rohit provided in the concurrency issue #195 and the [Amazon instructions for setting up containers in ECS](https://aws.amazon.com/getting-started/hands-on/deploy-docker-containers/),  below is a proposed initial deployment architecture:

1) Amazon RDS PostgreSQL database
2) S3 storage for the media folders
3) Containers for the REDIS and Python application using Amazon Elastic Container Registry for deployment
4) Elastic load balancing for the front-end

Initially we can limit the number of containers until we test out the concurrency of the application.

@rtgdk @kmehant @Ugtan Let me know any thoughts on the above proposal.

**Comment by goneall** [comment]
I tried out 3 different container deployment environments on AWS:

- Elastic Container Service (ECS)
- Elastic Kubernetes Service (EKS)
- Docker running on an EC2 instance

The container service looks promising, but is proprietary to AWS.  I was able to easily get an instance running, but it doesn't have the management flexibility of Kubenetes.

EKS was a rather involved process, but has a lot of flexibility and utilizes the standard Kubenetes tools.  The [Kubernetes branch](https://github.com/spdx/spdx-online-tools/tree/kubernetes) details the setup and contains the configuration files for the setup.

The [deploy-aws-ec2 branch](https://github.com/spdx/spdx-online-tools/tree/kubernetes) includes the details for the setup and updated configuration docker-compose files and a few other configuration fixes.  This was the easiest and most controllable approach to deploying the containers.

**Comment by goneall** [comment]
@kmehant @rtgdk @Ugtan I am currently thinking of starting the EC2 instance documented in the [README-PRODUCTION.md](https://github.com/spdx/spdx-online-tools/blob/deploy-aws-ec2/README-PRODUCTION.md).  Also, feel free to review the commits in the branch.

We can upgrade to the EKS approach in the future when we need the additional scalability.

If you agree with the approach I can create a PR from the branch for a better review.  If you think we should start wit the ECS or EKS approach, let me know.

**Comment by rtgdk** [comment]
@goneall Yeah, lets go with EC2 for now. I checked the diff of [deploy-aws-ec2](https://github.com/spdx/spdx-online-tools/blob/deploy-aws-ec2/) branch, lgtm.

**Comment by kmehant** [comment]
@goneall ECS +1

**Comment by goneall** [comment]
This is somewhat described in the README-PRODUCTION.md in PR #212
