### ISSUE TITLE
Enhancement Request: Add Check License tab to spdx-online-tools

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#2]
The online tool https://spdx.org/spdxweb compares license text to the SPDX listed licenses.  It uses a text box input and output a list of matched licenses as a dialog box.

Adding this feature to the spdx-online-tools would allow us to consolidate the tools into one UI (not to mention the UI is better for the spdx-online-tools).

The code is currently implemented as an SPDX servlet, but simply calls the SPDX tools library.

The Java code that calls the library is the following:

```
LicenseCompareHelper.matchingStandardLicenseIds(licenseText)
```
where license text is the text in the textbox.

@rtgdk If you prefer, I can create a pull request with the Python code to implement this.

**Comment by rtgdk** [comment]
@goneall  Sure, go ahead with the Python code.
Yes, it would be better to have all the online tools under one app. I'll create a separate url for this license search and will work on the UI once it is linked with JPype.

**Comment by goneall** [comment]
@rtgdk I just pulled the latest.  I'll add the Python code and create a pull request

**Comment by goneall** [comment]
@rtgdk I added the code changes to a branch licensecheck-go, however I was not able to test it on my local machine.  I ran into issues trying to test on my local machine.  They may be JPype related.  The JVM is crashing at JPJavaEnv::GetArrayLength(_jarray*)+0x20.

I also tried the existing validate functionality and terminated the python runtime without any error message.  I wonder if I have a configuration issue with the JVM or JPype.

If you could try the license check code and see if it works in your environment.  If it does, feel free to merge it in.

**Comment by rtgdk** [comment]
@goneall  I'll go through the licensecheck code. Can you send the file you tried the validate tool with ?

**Comment by rtgdk** [comment]
I have update the python code. The JVM Thread was being detached before calling len function on matching_licenses. It works fine now. 
But it takes a lot of time( atleast 2 minutes ). When I tried the same on Eclipse, it again took the same amount of time. Whereas the java servlet returned the same result in less than 10 seconds. The input was the whole license text of AFL-1.1 in all the cases. I hope JPype returns the result much faster in production.

**Comment by goneall** [comment]
Thanks for finding the bug.  I'll pull the changes tomorrow and check it out.  The performance issue is the licenses being downloaded from spdx.org/licenses website.  This is only done once and cached as a static field in the ListedLicenses class.  I don't know if the caching will work with JPype.  We would want the class to stay loaded in the JVM so that the cached licenses are available for the subsequent calls to the Check License function.  If we can't cache the licenses, there is an option where the licenses are loaded locally from files which is faster, but it isn't kept current with the published listed licenses.

**Comment by rtgdk** [comment]
@goneall  I tested whether there was a cache or not. It took about 3 minutes for the first search. Later on, it didn't take more than 3 seconds. So I guess, the cache is working.

**Comment by goneall** [comment]
@rtgdk I updated with your fixes and it works reasonably well.  On I am getting subsecond response times on the second request (about 3 minutes on the first search), so the caching is working well.

If you are OK with the code, go ahead and merge the PR.

**Comment by rtgdk** [comment]
@goneall Merged. I'll just add ajax form submisson and result display in a pop up modal.
