### ISSUE TITLE
Update .gitignore to ignore .DS_store 

### ISSUE THREAD

**Issue by susg** [spdx/spdx-online-tools#20]
In macOS, temp/junk file named `.DS_Store` is created that stores custom attributes of its containing folder. Update gitignore to ignore such files.

**Comment by rtgdk** [comment]
Go ahead to solve this. Also, check out if gitignore file is something other than this.

**Comment by susg** [comment]
I could not find anyting else that should be ignored as of now. If I get I will update it.

**Comment by wking** [comment]
> In macOS, temp/junk file named `.DS_Store`…

This sort of thing is specific to the user environment, not the project.  I think the cleanest solution to that is to add it to your personal or system `gitignore` (e.g. `$XDG_CONFIG_HOME/git/ignore`, see `gitignore(5)`).  That protects all of your projects, without adding per-projects entries that users on other platforms don't need.
