### ISSUE TITLE
Change message when submitting license update request

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#215]
When there is a near match of a license when submitting a new license request, the user is prompted to compare the licenses. 
 When the user chooses the option that the licenses should match, an issue is submitted requesting the license to be updated.

The message displayed seems to indicate a new license request is submitted.  The message be changed to something like "A request has been sent to update the license text to match".

**Comment by Ugtan** [comment]
> When there is a near match of a license when submitting a new license request, the user is prompted to compare the licenses.
When the user chooses the option that the licenses should match, an issue is submitted requesting the license to be updated.

@goneall If the license is a close match, the user is prompted to choose if the changes made by the user is substantial or if they think the licenses should match. 

If the changes are substantial a new request i.e GitHub issue is created so "A new license request" makes more sense, thoughts?

If the license should match(the case you are talking about), a new pull request is added to the desired repository. If you want we could update the pull request title or body to display the message "A request has been sent to update the license text to match".

**Comment by goneall** [comment]
> If the changes are substantial a new request i.e GitHub issue is created so "A new license request" makes more sense, thoughts?

Their response indicates that the changes are not substantial and the licenses should match, so the issue created is correct.  It is just the message displayed back to the user isn't correct.  The message states that a new license request is submitted when in fact it is an issue requesting the licenses to match.

Only the message displayed to the user needs to be updated.  I thought the issue submitted to github was fine.

**Comment by goneall** [comment]
Resolved with PR #231
