### ISSUE TITLE
Need to configure License Text Diff

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#216]
This is an issue for the production instance.

Issues submitted to update the license text point to https://github.com///blob/master/3y7usicope.png which seem to be missing github account.

See https://github.com/spdx/TEST-LicenseList-XML/issues/77 for an example.

This likely needs to be configured.

**Comment by goneall** [comment]
@Ugtan Do you know what needs to be configured for the license diff repo?

Gary

**Comment by Ugtan** [comment]
@goneall Please check out this comment for info https://github.com/spdx/spdx-online-tools/pull/136#issuecomment-533274704. Also, Instead of hardcoding these, we should take these inputs from the environment variables just like we are using the `spdx-prod.env` in production.

**Comment by goneall** [comment]
Resolved with PR #217
