### ISSUE TITLE
Installation Error: No Module named secret

### ISSUE THREAD

**Issue by vcmgc27** [spdx/spdx-online-tools#233]
Hi

When executing "python src/manage.py migrate" . Getting below error.

(venv) root@ip-10-68-216-147:/opt/spdx/spdx-online-tools# python src/manage.py migrate
Traceback (most recent call last):
  File "src/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/spdx/spdx-online-tools/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/spdx/spdx-online-tools/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/opt/spdx/spdx-online-tools/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/opt/spdx/spdx-online-tools/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/spdx/spdx-online-tools/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/spdx/spdx-online-tools/src/src/settings.py", line 14, in <module>
    from secret import getGithubKey, getGithubSecret, getSecretKey, getOauthToolKitAppID, getOauthToolKitAppSecret, getDiffRepoGitToken, getDiffRepoWithOwner
ImportError: No module named 'secret'

Help in resolving this and install this application in our ubuntu instance.

Thanks.

**Comment by goneall** [comment]
See the [developer secrets section of the README](https://github.com/spdx/spdx-online-tools/blob/master/README.md#github-developer-sensitive-data).  You need to create the secrets file on your local system.

**Comment by vcmgc27** [comment]
Need to create below values in .env file right in /spdx-online-tools/src/src directory right?

ONLINE_TOOL_GITHUB_KEY
ONLINE_TOOL_GITHUB_SECRET
DJANGO_SECRET_KEY
OAUTH_APP_ID
OAUTH_APP_SECRET

Created Github key and github secret, Need help in getting Django secret key, OauthAPPID and OAuthAppSecret. Based on the steps here: https://github.com/spdx/spdx-online-tools/blob/master/README.md#django-oauth-toolkit-app

Ran this command "python src/manage.py createsuperuser" . This also gave ImportError: No module named 'secret'.

Help me in this.

Thanks

**Comment by goneall** [comment]
This may be due to the `.gitignore` set to ignore secrets.py file.  

I created a PR to remove the .gitignore for the secrets.py file.

@vcmgc27 try fetching and switching to the branch `addinsecret`.  It that works, I can merge in the changes.

**Comment by rtgdk** [comment]
@vcmgc27  @goneall I think the error is because tool is being setup in python3. Since [implicit relative import does not work in python3.](https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html#python-2-vs-python-3) The `master` branch works on python2.7 for now. There's another branch - `rtgdk_python3` where we are migrating tool to python3. Most of the changes are done in #205 although some tests are failing. You can maybe use this branch to setup the tool in your ubuntu instance or create a virtualenv with python2.7 and follow the [README.md](https://github.com/spdx/spdx-online-tools#requirements-linuxdebianubuntu)

**Comment by vcmgc27** [comment]
Thanks @rtgdk will try this branch mentioned above. Also, need help in creating this env file with below details:
ONLINE_TOOL_GITHUB_KEY
ONLINE_TOOL_GITHUB_SECRET
DJANGO_SECRET_KEY
OAUTH_APP_ID
OAUTH_APP_SECRET

**Comment by rtgdk** [comment]
@vcmgc27 The instructions to setup is given here - https://github.com/spdx/spdx-online-tools#github-developer-sensitive-data
For setting up Github Oath app- You can follow https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app/

**Comment by nishantc7** [comment]
Using `virtualenv -p python2 venv ` 
`source venv/bin/activate` as 2nd step in installation mentioned in readme for master branch should work until we move the branch to python3 because the default virtualenv is for python3. Views? @rtgdk

**Comment by rtgdk** [comment]
@nishantc7 Not a big issue. Before the steps, it is clearly mentioned to install Python2. Also I think `virtualenv -p python2 venv` will work only if python2 is installed on the system.

Since we will be migrating to python3 soon, I don't think this change is needed.

**Comment by rtgdk** [comment]
Should not face such issues now. We have also migrated to Python3 now. Closing the issue
