### ISSUE TITLE
Tools.spdx.org GitHub oauth redirect uri mismatch

### ISSUE THREAD

**Issue by alandtse** [spdx/spdx-online-tools#235]
This is probably covered in #221 but adding it in case it isn't tied to SSL specifically

The http://13.57.134.254/app/submit_new_license/ page currently fails the GitHub OAUTH with a HTTP 500 because it redirects back to the static IP.

The oauth returned link from GitHub indicates the error is a uri mismatch because it doesn't match the registered callback:
http://13.57.134.254/oauth/complete/github/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=YiuITr12Qdkdyin9ljgw8dgWqMVZaQuU

**Comment by goneall** [comment]
thanks @alandtse for reporting this.

When I tried, I was able to successfully logout/login if I used the old static IP address http://13.57.134.254/ however, if I access the site through https://tools.spdx.org, I got the 500 error mentioned above.

@alandtse can you confirm that it works when accessing the site using the IP address?

Updating the configuration to redirect to https://tools.spdx.org didn't seem to work and it also broke the direct access.

I think the only way to make both of these work is to change the redirect method to not rewrite the URL's - this also requires disabling SSL for the http://13.57.134.254 site.

Once we switch over to the new production site, the redirect will go away and we'll be able to re-enable SSL.

For reference, the current redirect is managed by nginx with the configuration file at https://github.com/spdx/spdx-online-tools/blob/master/data/nginx/app.conf

**Comment by alandtse** [comment]
Yes, straight IP address works for me.

**Comment by goneall** [comment]
Resolved with PR #236
