### ISSUE TITLE
Adding support for Python3

### ISSUE THREAD

**Issue by techytushar** [spdx/spdx-online-tools#24]
When I try to run the app with `Python 3.5.2` the following error occur:
1. `except jpype.JavaException, ex` is not supported can be changed to `except jpype.JavaException as ex`
2. `from models import` gives `Import error` can be changed to `from api.models`
3. `from urlparse import urljoin` also gives `import error` as there is no module named `urlparse` in Python3 it has been changed to `urllib.parse`
4. Also the `jpype` gives error while installing for python3.6

1 and 2 are fixable but I cannot find a way to fix 3

**Comment by rtgdk** [comment]
Although Django 1.11 is the LTS version, which will be supported for around 3 years. We can create a separate branch to work on Python 3 with Django 2. This would be a good head start.

For 4th, we can use https://pypi.python.org/pypi/JPype1-py3 , although it is technically in development phase. BTW jpype requirements suggest using Python2.7+, so I think it should work fine with python3.6 . What is the exact error you are facing? You can look through the original repo to find your issue or open new one. https://github.com/originell/jpype/

**Comment by Dhiraj240** [comment]
@rtgdk does this issue still need development? I would like to work on it

**Comment by rtgdk** [comment]
@Dhiraj240 I think @techytushar has already pushed #59 for this issue back in Dec 2018. But you can go ahead and check if everything works right now. If not, we would like to migrate to Python3 and Django2 in master. So, we would need a hand to merge the python3 support to master.
Some work is already done in https://github.com/spdx/spdx-online-tools/tree/python3
With this, you can also resolve #58 .

**Comment by Dhiraj240** [comment]
Alright, I will work on this coming weekend and check the files which require changes.

**Comment by SidharajYadav** [comment]
How i can contribute
please guide me
I like to solve this problem

**Comment by autoantwort** [comment]
Can be closed, python 3.7 is currently used.

**Comment by goneall** [comment]
Thanks @autoantwort for reviewing and updating the issues
