### ISSUE TITLE
Add / modify fields for New License Request

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-online-tools#240]
Followup from #1108, filing here at @goneall's request:

From @vmbrasseur:

> The current 'new license request' issue template (by way of tools.spdx.org, I believe) has these fields:
> 
> License Name:
> Short identifier:
> License Author or steward:
> Comments:
> Standard License Header:
> URL:
> OSI Status:
> It may make sense to evolve this template a bit to include more of the information needed for the inclusion principles. For instance, maybe add a field for listing example projects using the license.
> 
> What do folks think of reconsidering the fields on this template?

I'm +1 on adding a field to list URLs to example projects using the license, this is info we almost always want.

I'll take another look through the inclusion principles to see if there's more we want to ask.

**Comment by goneall** [comment]
resolved with PR #248
