### ISSUE TITLE
[Suggestion] Automatic Output File Name

### ISSUE THREAD

**Issue by RishabhBhatnagar** [spdx/spdx-online-tools#241]
While testing [/app/convert/](http://52.32.53.255/app/convert) converter, I was required to enter the name for the converted file. It would've been better if the application auto-set the converted file's basename the same as that of the input file.
For example: if "input.rdf" is the input file that is to be converted to xls format, the converted file name could've been set to "input" as a placeholder.

**Comment by js899** [comment]
cani take up this issue ? plz assign it to me

**Comment by shalika10** [comment]
hey @RishabhBhatnagar  can you explain the problem statement  in detail with example ?would like to contribute to it

**Comment by RishabhBhatnagar** [comment]
Hello @shalika10, In the [/app/convert](http://52.32.53.255/app/convert/) website, upon uploading a document, the label corresponding to `Converted File Name` must set the placeholder value same as that of the uploaded file's name.
An example is already provided in the issue description.

**Comment by hardikkat24** [comment]
Hello @RishabhBhatnagar, I would like to work on this issue.
