### ISSUE TITLE
Probably Lossy or Erroneous Conversion

### ISSUE THREAD

**Issue by RishabhBhatnagar** [spdx/spdx-online-tools#242]
Converting [file](https://drive.google.com/file/d/1Z0twYcbzI5VjyT4uoTaE7aLG2-r5eiWp/view?usp=sharing) back and forth between rdf/xml and tag caused the [/app/convert/](http://52.32.53.255/app/convert) to panic.

I was able to convert the rdf/xml file to tag-value format but while retrieving the rdf/xml file, it raised the following error:
`Error creating SPDX Analysis: Invalid license expression. Expecting more operands.`

It is not directly related to online-tools. But an error due to the internal tools being used.
I've not worked with tag-value file format much to point out an issue. 

Hence leaving an open-ended issue to be debugged.

**Comment by goneall** [comment]
There were 2 issues in the RDF/XML files that needed to be changed:

- Removed 2 concludedLicense definitions for one of the packages - the cardinality is 1
- Replaced the URI's http://spdx.org/licenses/NOASSERTION and http://spdx.org/licenses/NONE with http://spdx.org/rdf/terms#noassertion and http://spdx.org/rdf/terms#none

An updated test file is attached.

I also updated the SPDX tools to address an issue with the listed licenses when they are not defined within the RDF package in PR #247 
[SPDX2_time-1.9.tar.gz_1535120734-spdx-corrected.rdf.txt](https://github.com/spdx/spdx-online-tools/files/5433799/SPDX2_time-1.9.tar.gz_1535120734-spdx-corrected.rdf.txt)

**Comment by goneall** [comment]
Resolved in PR #247
