### ISSUE TITLE
license request tool: add text to top of page

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-online-tools#252]
Can we add some text to the top of this page along the lines of:

"Please review the SPDX License List [license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md) before submitting a new license. 
Once you have submitted a license, please follow the [issue in Github](https://github.com/spdx/license-list-XML/issues) and be prepared to help create the required files if the license is accepted for submission."

with a link to the inclusion principles and Github repo/issues

**Comment by swinslow** [comment]
"Please review the SPDX License List license inclusion principles before submitting a new license.
Once you have submitted a license, please follow the issue in Github and be prepared to help create the required XML and test text files if the license is accepted for submission."
