### ISSUE TITLE
Problem when Validating 2.2 Tag/Value file.

### ISSUE THREAD

**Issue by kestewart** [spdx/spdx-online-tools#255]
When trying out the test site, and using validate I get.

No enum constant org.spdx.tools.SpdxToolsHelper.SerFileType.Tag

Test file is from:
https://github.com/rjb4standards/REA-Products/blob/master/SAG-PM.spdx
(using Tag/Value)

**Comment by goneall** [comment]
Resolved in PR #256 - Note: the staging/test website http://52.32.53.255/ has not been updated.  It will be updated prior to going into production
