### ISSUE TITLE
None Attribute Error processing LicenseListXML Issues

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#259]
While deploying the production environment, a None attribute error (e.g. null pointer) occurred in the `get_license_data` function of utils.py.  This was due to a search not yielding a result in the following line: 

`licenseIdentifier = re.search(r'(?im)short identifier:\s([a-zA-Z0-9|.|-]+)', licenseInfo).group(1)`

This may be resolved with PR #258 where the exception is basically ignored.  This assumes, however, that the error is due to an improperly formatted issue.

This assumption should be verified to make sure there isn't a different cause (e.g. the incorrect pattern to search).

**Comment by rtgdk** [comment]
From the flow, it looks like it checks the license list repo for all the closed issue and searches for  `short identifier: <id>` in the issue body. One fix would be to allow any no of spaces between `:` and `<id>`. 
`\s+([a-zA-Z0-9|.|-]+)`
For all issues raised by the online tools, we have only 1 space in between. (utils.py line 340)

**Comment by goneall** [comment]
This has been resolved in PR #258 and deployed to production.
