### ISSUE TITLE
Bytes to str conversion results in malformed xml in Python3

### ISSUE THREAD

**Issue by rtgdk** [spdx/spdx-online-tools#272]
Discussion - https://github.com/spdx/spdx-online-tools/pull/205#issuecomment-742222481

**Comment by goneall** [comment]
I did some more research and the data is stored incorrectly in the database.

In the Python3 version, prepended with b:

```
>>> result[0][7]
'b\'<SPDXLicenseCollection xmlns="http://www.spdx.org/license"><license isOsiApproved="true" licenseId="testid" name="Test License [Please Ignore]" listVersionAdded=""><crossRefs><crossRef>http://source1.com</crossRef></crossRefs><standardLicenseHeader /><notes /><text><p>test not there yet</p></text></license></SPDXLicenseCollection>\''
```

I looked at the production database, and the string is just stored as XML:

```
<SPDXLicenseCollection xmlns="http://www.spdx.org/license"><license isOsiApproved="false" licenseId="V8" listVersionAdded="" name="V8 Project License"><crossRefs /><standardLicenseHeader /><notes /><text><p>Copyright 2006-2011, the V8 project authors. All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:</p><list><list><item><bullet>*</bullet><p>Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
     Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the following
      disclaimer in the documentation and/or other materials provided
      with the distribution.
     Neither the name of Google Inc. nor the names of its
      contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.</p><p>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</p></item></list></list></text></license></SPDXLicenseCollection>
```

**Comment by goneall** [comment]
The xml string is created by a call to `xml.etree.ElementTree.tostring(root, method='xml')` at https://github.com/spdx/spdx-online-tools/blob/408cd70933b1814e4002d7172d01f12bb535c132/src/app/generateXml.py#L155

The return return value is:

`b'<SPDXLicenseCollection xmlns="http://www.spdx.org/license"><license isOsiApproved="true" licenseId="testid" name="Test License [Please Ignore]" listVersionAdded=""><crossRefs><crossRef>http://source1.com</crossRef></crossRefs><standardLicenseHeader /><notes /><text><p>this doesn\'t match anything</p></text></license></SPDXLicenseCollection>'`

The model defines XML to be a textField at https://github.com/spdx/spdx-online-tools/blob/408cd70933b1814e4002d7172d01f12bb535c132/src/app/models.py#L37

This is where my Python knowledge runs out - I'm not sure why the strings are stored differently between Python2 and Python3.

Suggesting that the fix be to store the data without the `b'<...` so that it is compatible with the existing database.

**Comment by rtgdk** [comment]
Yeah, turns out the issue is with the module - `import xml.etree.ElementTree as ET`. Went into the `ElementTree` codebase it returns bytes by default if encoding is not provided. 2 ways to do this
Either do `xmlString = xmlString.decode("utf-8")` or use `xmlString = ET.tostring(root, method='xml', encoding='unicode')`
More info - https://stackoverflow.com/questions/15304229/convert-python-elementtree-to-string

**Comment by rtgdk** [comment]
@goneall So as I understand correctly, Python2 database looks fine - all the relevant fields are stored as normal string right? This issue occurred because you saved some license with Py3 which saved it as bytes. Right?

If yes, then to fix this - we need to go through the codebase to find more usage of str(..), unicode(..)) etc and add decoding/encoding accordingly. If no, then we would have to fix the current database itself since we can't handle every other unicode/ascii case. We need to have out database consistent.

**Comment by goneall** [comment]
> So as I understand correctly, Python2 database looks fine - all the relevant fields are stored as normal string right? This issue occurred because you saved some license with Py3 which saved it as bytes. Right?

Yes - that is correct

> If yes, then to fix this - we need to go through the codebase to find more usage of str(..), unicode(..)) etc and add decoding/encoding accordingly.

I can think of two things we could do:

- Grep the code base for `str(` and `unicode(` then review the occurrences
- Run some manual tests to create database entries and compare them to the Python2

The latter would catch issues which may be caused by library calls to str(..) and unicode(..).

@rtgdk Are there any other steps you can think of?  Also, should we grep for any other patterns?

**Comment by rtgdk** [comment]
Apart from `str(` and `unicode(` explicit conversions, we also need to check any implicit conversions as well like some module function call - eg: `ET.tostring(root, method='xml')`.
We can also grep `decode/encode/utf-8/unicode/`

**Comment by goneall** [comment]
This specific problem has been resolved with the PR #273  however, there are 2 new problems which now show up - issue #275 and issue #274

**Comment by goneall** [comment]
Resolved issues #275 and #274 with PR #276

**Comment by goneall** [comment]
I reviews all the calls to ET in utils.py which involve encoding.  Later this week, I'll grep for the other encoding related items.

Note that `open(...` also can have encoding issues.  I reviewed all the calls to open in views.py and fixed all the identified issues in PR #276

**Comment by goneall** [comment]
I reviewed the strings and found a couple of areas that should be looked at by someone more experienced in Python.  @rtgdk @Ugtan If you could take a look and see if there are any encoding issues.

The review was done on the branch [fixencodinggo ](https://github.com/spdx/spdx-online-tools/tree/fixencodinggo)which includes all the fixes to date.

The utils method get_license_data should be reviewed - it is hard to test in a non-production environment and includes a lot of string decoding:  https://github.com/spdx/spdx-online-tools/blob/4cd4e3146a2aa32951faf992a6f98efc58d2232f/src/app/utils.py#L459

The file https://github.com/spdx/spdx-online-tools/blob/fixencodinggo/src/api/views.py should be reviewed - it has some str's and other encode decodes.  I reviewed the file and didn't see anything obvious, but I could have missed something.

I'll attach 3 files from the string greps for reference:

[decode.txt](https://github.com/spdx/spdx-online-tools/files/5712888/decode.txt)
[encodestr.txt](https://github.com/spdx/spdx-online-tools/files/5712889/encodestr.txt)
[strs.txt](https://github.com/spdx/spdx-online-tools/files/5712890/strs.txt)

**Comment by rtgdk** [comment]
@goneall Updated PR with some more encode/decode changes. Regarding `str(` changes, I think we will be good without them. We just don't want bytes in our database.

**Comment by rtgdk** [comment]
This was fixed with python3 support
