### ISSUE TITLE
Merge app and api code under a common utils

### ISSUE THREAD

**Issue by rtgdk** [spdx/spdx-online-tools#287]
Right now, api `views.py` code is not updated with the changes in app `views.py`. There are some API which doesn't use anything from app source code. Not sure why, but it was a bad design decision to separate API and App code. We should have a common utility handling both API and app calls.

**Comment by hardikkat24** [comment]
@rtgdk Can you explain this issue in detail?

**Comment by rtgdk** [comment]
If you look at the api code for validate/convert/compare, you will see that it is quite outdated as compared to similar app code. We need to have API also go through the same functions as app calls (Maybe have a common utility that both of them of calls, or redirect API calls to app in some way or any other idea you can think of). Maintaining and testing will become a lot easier once these are merged. I assume it will be a big project (~ 2 weeks). 
Please discuss any other approach you have before you start this.
API request and response - https://github.com/spdx/spdx-online-tools/wiki/REST-API-Fields-Request-and-Response

**Comment by hardikkat24** [comment]
@rtgdk I would like to work on this. I'll take a look at both the app and api codebase and will discuss it here.
Thanks!

**Comment by rtgdk** [comment]
Fixed with #316
