### ISSUE TITLE
Create a link back to the SPDX main website

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#288]
We're adding a link to the online tools from https://spdx.dev website.  It would be good to have a link to the main SPDX web page.  Perhaps the upper-left could be an SPDX logo with a link to the main web page.

**Comment by Apoorvgarg-creator** [comment]
@goneall @rtgdk  Can I work on this issue?

**Comment by rtgdk** [comment]
@Apoorvgarg-creator Yes, you can pick this up.

**Comment by Apoorvgarg-creator** [comment]
@rtgdk Thank you. I have started working on this, Will make a PR as soon as possible.

**Comment by BassCoder2808** [comment]
Hi @rtgdk, I want to contribute to this issue if it is still open, but as per the comment by @goneall I had gone to the current website `https://spdx.dev/` and I think the feature has been added and the issue can be closed.

**Comment by goneall** [comment]
Fixed with PR #442
