### ISSUE TITLE
Failed to submit new namespace

### ISSUE THREAD

**Issue by pombredanne** [spdx/spdx-online-tools#292]
I tried to submit a proper new license namespace request for https://scancode-licensedb.aboutcode.org/
![spdx-Screenshot from 2021-02-13 12-33-57](https://user-images.githubusercontent.com/675997/107848948-12396380-6df8-11eb-8d68-a57485927cad.png)

and it failed:
![SPDX Screenshot from 2021-02-13 12-34-21](https://user-images.githubusercontent.com/675997/107848954-19607180-6df8-11eb-9ebe-197ea47da646.png)

the details are:

```
Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last):
  File "/spdx/src/app/views.py", line 289, in submitNewLicenseNamespace
    licenseNamespaceRequest.save()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, Philippe Ombredanne, Philippe Ombredanne, scancode, 2021-02-13 11:34:12.682874+00, pombredanne@nexb.com, , <SPDXLicenseCollection xmlns="http://www.spdx.org/license"><lice..., f, t, This namespace tracks all the ScanCode licenses, scancode, https://scancode-licensedb.aboutcode.org/, https://scancode-licensedb.aboutcode.org/, https://github.com/nexB/scancode-toolkit/tree/develop/src/licens..., f, null, null).


```
I would guess that an organization is needed. YET the org creation is an admin-only thing that requires a Django admin login which I do not have

**Comment by goneall** [comment]
Thanks @pombredanne for trying this out and the details.

I missed this in testing since I happened to have DJango admin.

I think the right solution for this is to not require Admin for adding organizations to the list.  Although, I don't remember all the details from the original workflow proposal for adding namespaces. @pombredanne let me know if you agree users should be able to add an organization.

**Comment by goneall** [comment]
In addition to allowing users to add the appropriate organization, we should validate the user input and provide form validation rather than have the back-end catch the errors.

**Comment by pombredanne** [comment]
> let me know if you agree users should be able to add an organization.

I think so.

If you do not mind to add an org for me for now as: 
- nexB inc.
that would be great and I would be able to move on to register my namespace at last ;)

**Comment by goneall** [comment]
@pombredanne I attempted t add nexB as an organization and got an error.

I'll open a second issue to track the error.

I noticed this was actually adding a DJango managed organization which I do not think is necessary.  I'm wondering if we should just remove the organization field and requirement.

**Comment by goneall** [comment]
Added issue #293 for the DJango issue.

**Comment by goneall** [comment]
@pombredanne Do feel free to suggest improvements/pull requests for this feature - I don't think it has had much user testing.  I'll try to help get it working, but Python is not my native language ;)

**Comment by goneall** [comment]
@pombredanne - @rtgdk and I were able to fix the database upgrade problem and we added NexB to the list of organizations.  Let us know if you run into any further issues.

I'll leave this issue open to track longer term solutions (such as not requiring admin access).

**Comment by pombredanne** [comment]
@goneall @rtgdk thank you ++
I tried again and I still get this:

> Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/spdx/src/app/views.py", line 289, in submitNewLicenseNamespace licenseNamespaceRequest.save() File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save force_update=force_update, update_fields=update_fields) File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields) File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table result = self._do_insert(cls._base_manager, using, fields, update_pk, raw) File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert using=using, raw=raw) File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1079, in _insert return query.get_compiler(using=using).execute_sql(return_id) File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql cursor.execute(sql, params) File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute return self.cursor.execute(sql, params) File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__ six.reraise(dj_exc_type, dj_exc_value, traceback) File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute return self.cursor.execute(sql, params) IntegrityError: null value in column "id" violates not-null constraint DETAIL: Failing row contains (null, Philippe Ombredanne, Philippe Ombredanne, scancode, 2021-04-14 20:54:47.927308+00, pombredanne@gmail.com, , <SPDXLicenseCollection xmlns="http://www.spdx.org/license"><lice..., f, t, A set of licenses detected by ScanCode toolkit, scancode, https://scancode-licensedb.aboutcode.org/, https://scancode-licensedb.aboutcode.org/, https://github.com/nexB/scancode-toolkit/tree/develop/src/licens..., f, null, 1).

**Comment by goneall** [comment]
@pombredanne Thanks for the second attempt and patience.  Looks like the migration problems have not been completely solved.  I'll take a look at the database and see if I can fix it.

**Comment by goneall** [comment]
@pombredanne I believe I fixed this issue.  I just submitted a test namespace and the request did not show any exceptions. 
 I did not have time to verify the entire function worked end to end, so there still may be some issues.

Would you mind giving it another try?

BTW - The issues are due to a migration problem with the database when we moved from one AWS instance to another.  I did look through all the tables this time for similar issues and I think we got them all.

**Comment by pombredanne** [comment]
@goneall Thank you ++
It works: https://tools.spdx.org/app/license_namespace_requests/2/
awesome!
