### ISSUE TITLE
Unable to register user on local machine

### ISSUE THREAD

**Issue by lkbhitesh07** [spdx/spdx-online-tools#296]
Hello, I'm Just done with the local setup but when I try to register it's not working, it just redirects me to Github 404 error as the redirect_uri is from my local machine.
I'm not sure that if I'm pointing in the right direction but in the readme file, you have mentioned some steps in `GitHub Developer Sensitive Data` to have the `.env` file in the `src/src` folder, actually I'm not able to follow that. Please help me I'm a bit new to all these things.
Thanks
@goneall @rtgdk

**Comment by thisisshub** [comment]
- Did you setup the Github Oauth App like described [here](https://docs.github.com/en/developers/apps/creating-an-oauth-app)?
- and then setup the user in website's `Application` section int the `localhost:8000/admin` after signing in with your `superuser` account? 
- Finally, follow the **Django Oauth Toolkit App** section mentioned in the [README](https://github.com/thisisshub/spdx-online-tools/blob/master/README.md)

**Comment by rtgdk** [comment]
@lkbhitesh07 Have a look at this issue if it helps - https://github.com/spdx/spdx-online-tools/issues/233

**Comment by rtgdk** [comment]
I hope this was fixed by following #233. Closing this
