### ISSUE TITLE
Instead of login using sign in and sign up.

### ISSUE THREAD

**Issue by lkbhitesh07** [spdx/spdx-online-tools#297]
Just want to propose a simple add-on. Whenever someone visits the site they see the login button, wouldn't it be great if we can have two buttons sign in and sign up to avoid confusion? Please do let me know your thoughts.
Thanks
@rtgdk @goneall

**Comment by goneall** [comment]
@lkbhitesh07 Since we don't collect or store any information information on the user that would typically be in a sign-up form, I don't think we need the sign-up option typically found in other sites.

@rtgdk Any thoughts on this one?

**Comment by rtgdk** [comment]
@goneall Totally agree with you. We use sign in with github just for submitting the license. For other tools, we don't require login - so having a sign up add-on is not useful.

**Comment by goneall** [comment]
@lkbhitesh07 Based on the above comments, I'm suggesting we close this issue.  I do appreciate you reviewing the app and looking for improvements, however.

**Comment by rtgdk** [comment]
@lkbhitesh07 Closing this issue. Feel free to reopen if needed.
