### ISSUE TITLE
License Submission tool: changes to Comments field

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-online-tools#300]
the legal team is getting a lot of submissions where the Comments field is empty. This is intended to be more than just a free-form comment field, so we discussed ways to make it more prominent and a better label.  To that end, can we change the following:
1) move Comments field to be at the top of the form, first field
2) change name to "Explain why this license meets the license inclusion principles" (instead of Comments) - let us know if that exceeds any character limit

A couple questions:
3) can we make this a required field?
4) can we have an active link in the field name (i.e., a link to the "license inclusion principles")?

thanks!

**Comment by swinslow** [comment]
For @jlovejoy's question 4 above -- the link would go to https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md

+1 to making this change, this would be excellent! I don't know the scope involved, but perhaps a good first issue for someone who's looking at contributing to the online tools?

**Comment by Purhan** [comment]
Hey there, I made a pull request:https://github.com/spdx/spdx-online-tools/pull/302
review will be appreciated :)

**Comment by rtgdk** [comment]
@jlovejoy @goneall This issue has been resolved in the new upgrade to python3. You can check this out on production - https://tools.spdx.org/.  Thanks @purhan for working on the initial changes.
