### ISSUE TITLE
Can SPDX report can be converted to SPDX 1.x

### ISSUE THREAD

**Issue by vcmgc27** [spdx/spdx-online-tools#303]
Hi Team,

Is there any way to convert SPDX 2.2 to SPDX 1.x?

Please direct me if there is an option.

Thanks for your help

**Comment by goneall** [comment]
@vcmgc27 I'm not aware of any command line or online utility that will down-convert versions.

I believe you can write a utility if you're familiar with Java using the older version of the [SPDX Tools](https://github.com/spdx/tools).  You would open the "from file" with the method https://github.com/spdx/tools/blob/d5c23fd9fe47f6732239764204f27d1edae6eb94/src/org/spdx/rdfparser/SPDXDocumentFactory.java#L97 then create the output document with the method https://github.com/spdx/tools/blob/d5c23fd9fe47f6732239764204f27d1edae6eb94/src/org/spdx/rdfparser/SpdxDocumentContainer.java#L197 then copy everything over to the new document.  I thought there was some helper methods to make the copying easy, but I couldn't find it with a cursory look.

It would be a bit of work and I haven't tried this myself, so there may be some unexpected compatibility issues.

Probably easier to upgrade to 2.2 ;)

**Comment by goneall** [comment]
@vcmgc27 - Since this issue is a bit old and we've moved on to later versions, I'm going to go ahead and close this.  If you think there is still a need to down converting to 1.X, we can re-open.
