### ISSUE TITLE
Update Java tools library

### ISSUE THREAD

**Issue by ianling** [spdx/spdx-online-tools#310]
I recently submitted https://github.com/spdx/Spdx-Java-Library/issues/53 (thanks a lot for working on it!)

The reason I submitted that issue was actually due to our SPDX files failing to validate here. Now that the code change for the above issue has been merged, would it be possible to update the Django application to use the new version of the Java library?

Thanks!

**Comment by goneall** [comment]
@ianling I'm working on a new release of the libraries - hoping to finish within the next 3-4 days.  I'll update the online tools once it is complete.

**Comment by ianling** [comment]
Closing, thanks a lot @goneall !

**Comment by goneall** [comment]
@ianling I just deployed the version to https://tools.spdx.org

Let me know if you run into any issues.
