### ISSUE TITLE
GitHub Issue template for spdx/license-list-XML

### ISSUE THREAD

**Issue by anthonyronda** [spdx/spdx-online-tools#321]
On the 2021-07-22 SPDX-legal call, I suggested an issue template for the license-list-XML repo. This would encourage issue submitters to provide all necessary information just like what's requested in the Submit New License tool. Currently, there are a number of submitters who are likely unaware of the submission requirements, and omit crucial information.

## Option 1 - button that redirects issue submitter to Submit New License tool (my recommended)

Using Github's issue template YAML, the New Issue page suggests using the Submit New License tool *instead of* creating an issue inside GitHub itself.

### [Example](https://github.com/codidact/qpixel/issues/new/choose)

![image](https://user-images.githubusercontent.com/1410433/126722608-d5eb057d-5cd3-40a5-b53b-d029badba4cb.png)

### Tradeoffs

None. I believe linking to the Submit New License tool on the New Issue screen is a net positive. If desired, users can still submit a New Issue to the repo just like they always have. This option doesn't need to be maintained unless the tool's URL path changes.

## Option 2 - Form Schema

This is the option I mentioned on the call. It requires that all responses are filled out as expected in a manner similar to an HTML `<form>` with some built-in validation.

### Example

![image](https://i2.wp.com/user-images.githubusercontent.com/1469659/122435700-20f37b00-cf90-11eb-8028-056c7449e555.gif?ssl=1)

### Tradeoffs

This reduces the potential for "tech rot" caused by GitHub API updates, as it seems the Submit New License tool has been broken by an API update in the past. Use of this would mean less tech debt for SPDX. But if this is implemented alongside the existing Submit New License tool, that means each new update to the expected fields would have to be implemented twice.

## Option 3 - Traditional Issue Template

Until recently, GitHub issue templates were just regular markdown files with front matter that described what the name and description of the issue template should be. This could be a low-tech solution to provide the submission requirements.

### [Example](https://github.com/Azure/azure-cli/issues/new/choose)

![image](https://user-images.githubusercontent.com/1410433/126723893-1a25b036-ecf1-4ba7-9436-074a10bd382d.png)

### Tradeoffs

Simplest to create and maintain: can edit and commit changes through GitHub's browser based text editor. Doesn't validate fields or prevent users from skipping questions, though users will usually know that they are expected to answer everything.

**Comment by jlovejoy** [comment]
@BassCoder2808 - I think we already did this via step 3... and step 1, and can close this issue - do you agree?

**Comment by BassCoder2808** [comment]
Yes @jlovejoy we can close this one as you correctly mentioned that we are doing the same through step 3 and step 1

**Comment by goneall** [comment]
Closing this issue per the above comments
