### ISSUE TITLE
Warning messages misspell 'Anonymous'

### ISSUE THREAD

**Issue by ralphie79** [spdx/spdx-online-tools#322]
The warning message generated during validation of an SPDX document misspells the word 'Anonymous' as 'Anonomous' as shown in the following screen capture:
![image](https://user-images.githubusercontent.com/15354043/128235764-9d0090e3-0881-48c0-888e-af332da70277.png)

**Comment by goneall** [comment]
Thanks @ralphie79 - Just made a PR to fix this in one of the dependent libraries: https://github.com/spdx/Spdx-Java-Library/pull/58/files

I'll keep this issue open until we update the online tools with the latest library
