### ISSUE TITLE
Online validation of JSON example file in spdx-spec fails

### ISSUE THREAD

**Issue by SamuraiAku** [spdx/spdx-online-tools#325]
I tried running the [official JSON example file](https://github.com/spdx/spdx-spec/blob/v2.2/examples/SPDXJSONExample-v2.2.spdx.json)  through the online validator at tools.spdx.org and it fails.  The error that I get is:
> Analysis exception processing SPDX file: Missing document namespace

Looking through the JSON file it appears most likely that the field it is looking for is called "spdxDocument".  See an [issue in spdx-spec](https://github.com/spdx/spdx-spec/issues/520) that discusses this.  But it's not the field that the validation tool is looking for.

**Comment by goneall** [comment]
@SamuraiAku Thanks for reporting the issue.

The reason the v2.2 version of the JSON example file is failing is the top level `"Document"` on line 2 which was reported as this [issue ](https://github.com/spdx/spdx-spec/issues/400) in the spec repo.  

This was removed in the 
 [later version of the JSON example](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXJSONExample-v2.2.spdx.json) on the development/v2.2.1 branch which verifies correctly.

**Comment by goneall** [comment]
Since we have the JSON schema and format issues covered in the [SPDX Spec repo issues](https://github.com/spdx/spdx-spec/issues), I'm going to close this issue.
