### ISSUE TITLE
Online tool throwing error during validate

### ISSUE THREAD

**Issue by rjb4standards** [spdx/spdx-online-tools#330]
Class org.spdx.tools.SpdxToolsHelper$SerFileType not found 

I tried tweaking the SPDX version to get past this i.e. 2.2, 2.3 but neither one worked.

Any insights you can provide will be appreciate. Much appreciate your help with this.

Here is the SPDX that I suspect is blowing up:
FileName: activemq-broker-5.8.0.jar
SPDXID: SPDXRef-e1053a26-ef7c-4562-a839-9876b5ce597c
FileContributor: Im the Licensor
FileType: BINARY
FileChecksum: SHA1: C473018AAF2B8C5C45F7F8A035F0FF571A69EABA
LicenseConcluded: NOASSERTION
LicenseInfoInFile: NOASSERTION
FileCopyrightText: NOASSERTION

**Comment by goneall** [comment]
@rjb4standards I wasn't able to reproduce the issue

Can you give it another try and let me know if it still happens?

From the error message, this may be another form of a known intermittent problem with the python/java bridge, issue #285 

I'll attached the file version I used to try to duplicate - it should just be a copy/paste of the above.
[validateerror.spdx.txt](https://github.com/spdx/spdx-online-tools/files/7491028/validateerror.spdx.txt)

**Comment by rjb4standards** [comment]
Will do, Gary.

**Comment by rjb4standards** [comment]
Just tested - everything is working fine now. Thanks...

**Comment by rjb4standards** [comment]
Test succeeded.
