### ISSUE TITLE
SPDX License List submission tool: add unknown option to OSI approved question

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-online-tools#336]
Can we add "unknown" or "don't know" to the drop-down options for the OSI-approved question?

**Comment by jlovejoy** [comment]
editing this issue to include 3 minor updates to submission GUI as per discussion on Feb 3 legal call

- [ ] add "unknown" to drop-down options for OSI Status question
- [ ] add note or pop-up on license steward/author question to put "unknown" if submitter doesn't know
- [ ] remove email address question (not really needed)

**Comment by jlovejoy** [comment]
@johnmhoran from legal team may look into this (may need a bit of pointers from @goneall  to get started)

**Comment by johnmhoran** [comment]
@jlovejoy Confirming our discussion in this morning's legal team call, I'd like to help with this if my skillset permits.  ;-]  A quick look suggests the tool uses a combo of Python (maybe including Django?) and Java ( with which I have no familiarity atm).  I suspect I might need some guidance on how to clone and get the tool working locally (especially what Java-related installations/inports are required).

**Comment by goneall** [comment]
@johnmhoran Thanks for the help!

This particular issue should only involve the Python/DJango code.

I can help you get things setup, but you may want to wait for @rtgdk to finish merging a bunch of code.

@rtgdk - Let us know when the Python 3 code is merged.

**Comment by johnmhoran** [comment]
That sounds like a good idea @goneall , and thank you!  Looking forward to working on this issue.

I noticed that the [README](https://github.com/spdx/spdx-online-tools#requirements-linuxdebianubuntu) refers to Python 2.6+ and 2.7.  Has the project already been updated from 2.x to 3.6 (or even higher), or is that perhaps what the upcoming merge is tackling?  (I couldn't tell from looking at the open issues and PRs.)

**Comment by goneall** [comment]
@johnmhoran Thanks again for helping out!

> Has the project already been updated from 2.x to 3.6 (or even higher), or is that perhaps what the upcoming merge is tackling? (I couldn't tell from looking at the open issues and PRs.)

That's exactly what's being tackled.  It's a rather significant change.  There is a branch @rtgdk is working on with the changes: rtgdk_python3

**Comment by rtgdk** [comment]
@johnmhoran @goneall @jlovejoy `python3` branch has been merged to `master` on April 4. Let me know if you want me to pick up this task.

**Comment by johnmhoran** [comment]
@goneall @jlovejoy @seabass-labrax @swinslow 

I was going to tackle this issue now that I've begun to familiarize myself with Django, but looking at this issue (and at issue #365), I see that @seabass-labrax has already done some work and his PR #370 was merged on May 25.  

However, at least on my machine (using Chrome), the tool's `OSI Status` dropdown (https://tools.spdx.org/app/submit_new_license/) does not yet include the `Don't know` option.  
![image](https://user-images.githubusercontent.com/11096678/176020031-8493e0b1-d7c3-4ca4-adfe-8c86eda09dab.png)

Please let me know if there's anything I can help with on this (or any other Django-/Python-related issues) -- I am by no means an expert but would very much like to contribute however I can.

**Comment by goneall** [comment]
@johnmhoran Thanks for offering to help!  The code for this has been merged, but it has not been deployed to the production website.  I plan on deploying this along with the 2.3 changes in a couple of weeks (it takes a bit of effort, mostly testing, for every release).

**Comment by johnmhoran** [comment]
Thanks @goneall .  👍

**Comment by jlovejoy** [comment]
@goneall @johnmhoran @seabass-labrax @swinslow - I'm going to close this issue, as 2 of the 3 points have been implemented. I'll open a new issue as per our discussion on the legal call today and add the "remove email" to that list :)
