### ISSUE TITLE
[Python3] Option to check license diff on submit license page before submitting

### ISSUE THREAD

**Issue by rtgdk** [spdx/spdx-online-tools#346]
A new tool - License Diff - was recently added for users to check existing licenses which matches the license text. Also, a link on submit license page was provided. After submitting license, we match the text with licenses which shows the matches if any. The code to check matches and generate diff is common among both the pages. It would be a good idea to give users an option to check the license text before submitting the license too - using the License diff tool itself without redirecting to another tab.

**Comment by rtgdk** [comment]
Old changes was added as part of #345 PR

**Comment by BassCoder2808** [comment]
Hi @rtgdk I would like to work on this issue if it is still open, it would be great if you could tell me how to start with it

**Comment by rtgdk** [comment]
@BassCoder2808 Check the `License Diff` tool code in views. It provides information on whether the license text matches with already existing one. If we can provide this functionality via a button on submit licence page, then if would be a lot better and users can directly match licenses on the same page itself without navigating.

It's an additional UI feature since we already have the supported backend.

**Comment by BassCoder2808** [comment]
Hi @rtgdk , can you please review the #461 which will solve this above issue, and please let me know if anything else needs to be added or changed in that

**Comment by jlovejoy** [comment]
@rtgdk @BassCoder2808 - what is the status on this one? I don't think it was in @BassCoder2808 proposal, but if there is time, would be a great thing to work on!

**Comment by goneall** [comment]
It looks like this was fixed in PR #461 - @jlovejoy @rtgdk @BassCoder2808 - if you could confirm we can close this issue

**Comment by BassCoder2808** [comment]
yes, this has been done as well as far as I remember @goneall
