### ISSUE TITLE
License Diff Issues

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#355]
The new License-Diff feature has a couple of issues:

- It is similar to license-check functionality
- If you have a close match (e.g. just remove one or two words), it shows an exact match
- If you remove too many words from the license, it statues no match to any license

Suggest we remove this menu item / feature until the above issues are resolved.

**Comment by rtgdk** [comment]
@goneall Yeah I totally agree. I also noticed the same and did mention this in one of the emails before. Even the code is mostly same between license diff and submit license page (post check). A better way will be to use the same in pre check for submit license page or give this the user an option to run this. Have opened a similar issue here - https://github.com/spdx/spdx-online-tools/issues/346
