### ISSUE TITLE
Submit new license generates Python exception

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#361]
Submitting a new license generates the following error:

```
Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/spdx/src/app/views.py", line 158, in submitNewLicense matches, issueUrl = utils.check_new_licenses_and_rejected_licenses(licenseText, urlType) File "/spdx/src/app/utils.py", line 500, in check_new_licenses_and_rejected_licenses matches = get_close_matches(inputLicenseText, licenseData) File "/spdx/src/spdx-license-matcher/spdx_license_matcher/computation.py", line 21, in get_close_matches licenseName = key.decode('utf-8') AttributeError: 'str' object has no attribute 'decode'
```

**Comment by goneall** [comment]
@rtgdk If you could take a look when you get a chance

This only occurs on the production instance - I tested it locally and it worked fine

**Comment by rtgdk** [comment]
@goneall Sure, I'll take a look.

**Comment by goneall** [comment]
from [this stackoverflow article](https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error), it looks like we can just remove the `decode('utf-8')` from the spdx-license-matcher computation.py file.

I'll test this out on the production instance and if it works, I'll create a PR.

I did a grep of the license-list-matcher source to see if this was a problem anywhere else.  I did find another call to `decode('utf-8')` in [utils.py](https://github.com/spdx/spdx-license-matcher/blob/master/spdx_license_matcher/utils.py) but it looks like it is on byte array which should not be an issue.  @rtgdk please confirm this.

**Comment by goneall** [comment]
In looking at the license-matcher code, there a try/except block that calls without the decode.  When I changed `Except IOError:` to just `Except:` to allow catching of the attribute error, it worked.

I'll create a PR with the change.

**Comment by goneall** [comment]
@rtgdk [PR](https://github.com/spdx/spdx-license-matcher/pull/20) is ready for review.

**Comment by rtgdk** [comment]
Yeah, the actual exception raised in python3 is `AttributeError` not `IOError`.
