### ISSUE TITLE
New License form: Add value to OSI Status

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-online-tools#365]
https://tools.spdx.org/app/submit_new_license/: In the "OSI Status" field, should add a new value "Unknown" to the drop-down list.

**Comment by swinslow** [comment]
@seabass-labrax looks like you might have already started in on this one  :)  ("Don't know" is fine also rather than "Unknown")

**Comment by seabass-labrax** [comment]
Right'o! I'll send a PR shortly... :smiley:

**Comment by rtgdk** [comment]
Closed with #370
