### ISSUE TITLE
New License form: Add text next to label for License Steward

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-online-tools#366]
https://tools.spdx.org/app/submit_new_license/: Next to the label for "Who is the license author or license steward?", add text stating "(If not known, put 'Unknown')"

**Comment by sidtohan** [comment]
I would be willing to work on this issue. Can you please guide me on how to get started?

**Comment by sidtohan** [comment]
I have made a PR for this issue. Can you please have a look and tell if something else also needs to be done.
PR:  #375

**Comment by rtgdk** [comment]
Closed with #375
