### ISSUE TITLE
New License form: Remove the Email Address field

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-online-tools#367]
https://tools.spdx.org/app/submit_new_license/: Remove the "Email address" field

**Comment by Harixomxsingh** [comment]
hey there i working on it,

**Comment by jewishmoses** [comment]
Is this sufficient enough? https://github.com/spdx/spdx-online-tools/pull/379

**Comment by goneall** [comment]
@jewishmoses Thanks for contributing the fix.  From a quick look, the PR should fix the issue.

Have you tested it out in you development environment?

**Comment by jlovejoy** [comment]
@goneall @jewishmoses - what is the status of this? Looks like #379 needs a bit more work before it can be merged?

**Comment by goneall** [comment]
@jlovejoy @jewishmoses - I just wanted to make sure we did some amount of testing before I merge this in.  Once it's been tested, I'll merge.
