### ISSUE TITLE
License XML Editor: error when submitting

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-online-tools#369]
https://tools.spdx.org/app/edit_license_xml/142/ (or editing other licenses through the XML editor): When clicking "Submit Changes" and then "Confirm", getting an error about getting the ref to the master branch.

**Comment by jlovejoy** [comment]
@goneall  think it may have to do with SPDX license list repo changing from "master" to "main" 

submitted #397

**Comment by goneall** [comment]
This has been fixed with PR #417 

Unfortunately, there is a similar issue #423 

Closing this issue as resolved.
