### ISSUE TITLE
Validating an SPDX file with colon in name fails

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-online-tools#376]
In the online validator, I try to validate a file called `mariadb:latest.spdx`

I get a banner with the following error message: 

```
File /spdx/src/app/media/AnonymousUser/1654771839/mariadb%3Alatest.spdx not found.
```

**Comment by rtgdk** [comment]
@vargenau Which OS are you on when you upload this file? colon are not prohibited in windows world. Can you try without colon filename?

**Comment by vargenau** [comment]
It was a Linux machine, Ubuntu.

The bug is that the colon ":" has been encoded as "%3A". It should not have been.

**Comment by BanulaKumarage** [comment]
Hi, @rtgdk I am working on a windows environment. As you said, colons are prohibited in windows. Does this error occur in other characters except for the colon? If so I can try with that to reproduce the error. Otherwise is there any other way to reproduce this error? Please assist me on this.

**Comment by rtgdk** [comment]
@BanulaKumarage You can try to download a file which has colon in it's name and try opening it in Windows or through the onlint tool. You should be able to reproduce it.

There should a way to escape colon character or rename it before opening in windows.

**Comment by BanulaKumarage** [comment]
Thanks @rtgdk I will try that

**Comment by BanulaKumarage** [comment]
> @BanulaKumarage You can try to download a file which has colon in it's name and try opening it in Windows or through the onlint tool. You should be able to reproduce it.
> 
> There should a way to escape colon character or rename it before opening in windows.

when I tried to download such a file, it automatically renamed the file as follows.

![image](https://user-images.githubusercontent.com/63106638/229342293-2e0ca7f6-6b28-42df-84af-2fb877ca52e1.png)

**Comment by BanulaKumarage** [comment]
![image](https://user-images.githubusercontent.com/63106638/229349927-4872f923-e1b8-4edb-9218-f90fd907f117.png)

Recreated the issue. Working on it

**Comment by BanulaKumarage** [comment]
@rtgdk @vargenau Made PR #460 to fix this. Please review.

**Comment by vargenau** [comment]
Hi @BanulaKumarage 
I cannot test if the fix is not deployed.

**Comment by vargenau** [comment]
Has the fix been deployed on https://tools.spdx.org/app/validate/ ?

I still have the error.

**Comment by BanulaKumarage** [comment]
> Has the fix been deployed on https://tools.spdx.org/app/validate/ ?
> 
> I still have the error.
> 

Its not merged it yet.

**Comment by vargenau** [comment]
This has been fixed in  https://github.com/spdx/spdx-online-tools/releases/tag/v1.2.1

You can close the ticket.
