### ISSUE TITLE
Error when trying to validate a larger TV file

### ISSUE THREAD

**Issue by OliverFendt** [spdx/spdx-online-tools#386]
I tried to validate the SPDX2TV file of OpenSSL 3.0.5, but I received the following message:
![image](https://user-images.githubusercontent.com/15192452/187530422-29484297-3c11-4ba9-a375-eaf414508e6a.png)

When trying to vaildate a smaller file everything works fine.

Pleas find the SPDX file here for further investigations.
[openssl-3.0.5-SPDX2TV.spdx.zip](https://github.com/spdx/spdx-online-tools/files/9456195/openssl-3.0.5-SPDX2TV.spdx.zip)

Thank you very much

**Comment by goneall** [comment]
@OliverFendt I was able to duplicate the problem.  It seems to be taking a very long time to validate - >30 seconds which is likely causing a timeout.

When I validate the same file on my local machine, it takes less than a second.

I'll see if I can isolate the performance problem.

**Comment by goneall** [comment]
@OliverFendt - In the mean time, you can use the [Java command line tool](https://github.com/spdx/tools-java).  [Release 1.1.0](https://github.com/spdx/tools-java/releases/tag/v1.1.0) is the same code that is running validate for the online tools - apparently much slower in the online instance.

**Comment by goneall** [comment]
I've also duplicated the problem running the online tools on my local machine - same hardware as running the Java tools verify.  

Running the tools-java verifies the same file approximately 10 times faster than the online tools (4 seconds compared to 43 seconds).

CPU is at 121% on average during the run, there seems to be plenty of memory.

I can think of two possible issues:
- There is something outside of the call to Java that is taking all the time
- The JVM is somehow miss-configured (e.g. to little memory available)

I would like to run some kind of JVM analyzer on the JVM running in the container, but I'm not quite sure how to do that.

I'll see if I can add some instrumentation in the code to confirm the is being spend within the Java code.   May take me a couple of days.

**Comment by goneall** [comment]
@OliverFendt It looks like my previous analysis was based on some bad test data on my part - the validate is now taking the same 40 seconds or so on my machine - so we probably need to increase a timeout to allow this to complete without error.

**Comment by goneall** [comment]
I can only find 2 timeout values:
- https://github.com/spdx/spdx-online-tools/blob/92b5a4f56873258284b84b05aec9a929dc0fa7b0/supervisor_api.conf#L7
- https://github.com/spdx/spdx-online-tools/blob/92b5a4f56873258284b84b05aec9a929dc0fa7b0/src/app/templates/app/validate.html#L133

These are set to 4 minutes and 10 minutes if I understand the code correctly. 

The website times out after approximately 30 seconds.

I'm also not getting the same timeout when running the container on my local machine.

I suspect there is a timeout unique to the production instance.  We run nginx as a reverse proxy - one possibility.

Could use some help from someone with more sys admin/networking/configuration experience on this one - but I'll keep looking.

**Comment by goneall** [comment]
Narrowed it down - looking at the logs, I'm getting the following error:

```
[2022-08-31 05:30:07 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:695)
```

**Comment by goneall** [comment]
Looks like the above error is generated from supervisor or gunicorn.  The config file for supervisor has `timeout=240`, so it should not be timing out after 30 seconds.

**Comment by goneall** [comment]
@OliverFendt This is now resolved - I patched the production system and created a PR to fix this permanently on the next update.
