### ISSUE TITLE
License submission-editor: generate txt file?

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-online-tools#399]
XML file can be generated from the license submission and it does a pretty good job. But then one has to create the text test file. Would it be possible to add this functionality so that when the PR is created, both files are added?

**Comment by BassCoder2808** [comment]
Hi, @jlovejoy I would be happy to contribute to this if the issue is still open. It would be really helpful if you could help me get started like what all needs to be done/change like to get a brief overview of the problem

**Comment by jlovejoy** [comment]
as per discussion - generate .txt file at point at which XML file is generated and pull request is made in Github

**Comment by goneall** [comment]
Solve with PR #489
