### ISSUE TITLE
Rename “XML Editor” to “License XML Editor” to clarify its intended use (was: Add support for other valid extensions)

### ISSUE THREAD

**Issue by silverhook** [spdx/spdx-online-tools#40]
<del>

Currently it seems the upload (to XML Editor at least) only accepts files with an `*.xml` extension.

According to §1.6.9 of the [SPDX Specification 2.1][spec] it 
> [s]hould be easy to recognize in a file system without opening the file.  A suggested naming convention is to use *.spdx (for tag-value format) and *-spdx.rdf for RDF format.

So while `*.spdx` for tag-value and `*-spdx.rdf` are not a required naming, they are conventions that the SPDX Online Tools should at least support.

</del>

<ins>

As explained by @goneall in the first comment below, the underlying issue seems to stem from the ambiguous name of the tool. A simple renaming should be enough.

</ins>
[spec]: https://spdx.org/spdx-specification-21-web-version#h.3dy6vkm

**Comment by goneall** [comment]
@silverhook The XML editor is designed to support the license list XML (https://github.com/spdx/license-list-XML), not the SPDX documents.  To make this clear, we should rename "XML Editor" to "License XML Editor"

**Comment by silverhook** [comment]
@goneall, ah, that explains a lot :) My bad for missing that detail. I think the renaming would be a good solution to the actual underlying problem.

I will rephrase this issue accordingly.
