### ISSUE TITLE
XML Editor creating new pull request for a new license

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#408]
Selecting a submitted license, choosing to "edit XML" then submitting a license (without any edits), produces the following error:

```
Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/spdxonlinetools/src/app/views.py", line 1219, in pull_request response = utils.makePullRequest(username, token, request.POST["branchName"], request.POST["updateUpstream"], request.POST["fileName"], request.POST["commitMessage"], request.POST["prTitle"], request.POST["prBody"], request.POST["xmlText"], False) File "/spdxonlinetools/src/app/utils.py", line 192, in makePullRequest response = requests.put(commit_url, headers=headers, data=json.dumps(body)) File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps return _default_encoder.encode(obj) File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode return _iterencode(o, 0) File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default raise TypeError(f'Object of type {o.__class__.__name__} ' TypeError: Object of type bytes is not JSON serializable
```

**Comment by goneall** [comment]
@jlovejoy - Have you run into this issue?

**Comment by jlovejoy** [comment]
I don't think I have b/c I think in that scenario I always have done some editing - e.g., adding license list version and "beautify" - but I can try to see if I get the same error

**Comment by jlovejoy** [comment]
ok, tried using TTWL license submission, "edit XML", made no edits whatsover, and tried to submit and got this error:

" error occured while getting the ref of master branch. Please try again later or contact the SPDX Team."

hit back, then edited a couple things and tried to submit again, got same error :(

**Comment by goneall** [comment]
Interesting - I'm getting a different error.  Not sure why.

I'll deploy what we think is a fix to your error soon - but I have a feeling you'll hit an error.

**Comment by jlovejoy** [comment]
yup, as you suspected - I just tried to create XML for some of the licenses and got the same error. (I did use the XML text otherwise by simply copying it)

**Comment by goneall** [comment]
@jlovejoy - I just created a PR to fix this issue.  I'll update the online tools in the next week or two.

**Comment by goneall** [comment]
@jlovejoy 
Note: If you're using a fork of the repo in you're own personal repository, be sure to rename the master branch to main - otherwise you'll get an invalid reference specification error.
