### ISSUE TITLE
Missing part of Type in External Refs of XLSX Spreadsheet

### ISSUE THREAD

**Issue by yakuri** [spdx/spdx-online-tools#415]
In [SPDX Online Tool](https://tools.spdx.org/app/convert/), when converting with From:JSON, To:XLSX Spreadsheet, a part of Type in External Refs was missing.

JSON(From)
```
    "externalRefs" : [ {
      "comment" : "This is the external ref for Acme",
      "referenceCategory" : "OTHER",
      "referenceLocator" : "acmecorp/acmenator/4.1.3-alpha",
      "referenceType" : "http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301#LocationRef-acmeforge"
    } ],
```

XLSX Spreadsheet(To)
![image](https://user-images.githubusercontent.com/62694113/206676709-c9f8c976-8eff-4688-818f-0e83f0f21077.png)

Is this a bug or a specification?

**Comment by goneall** [comment]
@yakuri Thanks for raising this.

> Is this a bug or a specification?

Possibly a bug - but it would require a bit more investigation.  In general, if a value which is expected to be a URI has a prefix which is the same as the Document namespace, the prefix is removed.

For External Ref's, however, the prefix is typically removed if it is the SPDX namespace for references (`http://spdx.org/rdf/references`).

If translating the spreadsheet back to JSON properly translates the type field, then I would consider this a feature.  If it doesn't, I would consider it a bug.

The External Refs code is a bit complex and I would not be surprised if there is a bug here as well.  As long as it translates the spreadsheet back to the

**Comment by yakuri** [comment]
@goneall Thank you for your response.

I was able to convert the spreadsheet to JSON and convert the type field properly.
So I understood that it was a feature, not a bug.

Will you investigate this issue?
I will leave the issue open if you need to investigate.
If you do not need to investigate, close the issue.

**Comment by goneall** [comment]
@yakuri Thanks for the further investigation.  Base on your results, it looks like the tool is working properly.  I'll go ahead and close the issue.
