### ISSUE TITLE
Update to Latest NTIA-conformance-checker version

### ISSUE THREAD

**Issue by jspeed-meyers** [spdx/spdx-online-tools#428]
v0.2.0 now available: https://github.com/spdx/ntia-conformance-checker/releases/tag/v0.2.0

My tentative suggestion is to use the GitHub release again this time. But for the NEXT update, you could switch to the PyPI release. If you like to live dangerously though (🗡️!!), there is also a PyPI release, but its newness makes it untested.

PyPI release link: https://pypi.org/project/ntia-conformance-checker/#history

**Comment by goneall** [comment]
With the changes in the ntia-conformance-checker, it looks like we'll need to change the implementation.

Current call to the library is at https://github.com/spdx/spdx-online-tools/blob/43e330c70d4444e6cbf361c64b2fc0536aa6441f/src/app/core.py#L210

I'm thinking we'll want to change this to use the [SbomChecker](https://github.com/spdx/ntia-conformance-checker/blob/c24501dc5bcca905676cbccfba20a6e78692fe58/ntia_conformance_checker/sbom_checker.py#L14) passing in the file and calling the [printMissingComponents](https://github.com/spdx/ntia-conformance-checker/blob/c24501dc5bcca905676cbccfba20a6e78692fe58/ntia_conformance_checker/sbom_checker.py#L156) function and displaying the output as is.

The only thing I'm not completely clear on is the opening the file - it looks like I should pass in the filename `str(settings.APP_DIR + uploaded_file_url)` based on the current code, but I'm not sure if there isn't a more straightforward approach.

@jspeed-meyers @linynjosh - Let me know your thoughts.

**Comment by jspeed-meyers** [comment]
@goneall -- I thought the new changes might break something. :/ But hopefully the new printing mode is worth it :)

My intention was for both `sbom.print_table_output()` and `sbom.print_components_missing_info()` to be used inside `spdx-online-tools`. There are two ways (at least):

One is to treat `ntia-conformance-checker` as a CLI app and to call it with `subprocess`. For instance:

```python
result = subprocess.run(
    ["ntia-checker", "--output", "print", "--verbose", "--file", 
     settings.APP_DIR + uploaded_file_url],
    capture_output=True,
    text=True
)
print(result.stdout)
```

This way the table view is printed and any missing components are printed too. And the CLI entrypoint takes care of all of this and you don't have to use `ntia-conformance-checker` as a library.

It probably is also possible to use `ntia-conformance-checker` as a library, but there will (I think) need to be some small changes. I think https://github.com/spdx/ntia-conformance-checker/pull/81 will actually break the ability of `ntia-conformance-checker` to be a library. But a 10-minute code change should fix that.

I would therefore recommend the former path, but if you prefer the latter path, just say so and I can put in a new PR.

Regardless, I'm glad to debug this with you further if you get stuck.

**Comment by goneall** [comment]
@jspeed-meyers - I attempted using the command line with little success, if you could take a look at PR #432 

I suspect it is a setup issue - probably need to install the conformance checker as an app.

**Comment by jspeed-meyers** [comment]
@goneall - Sorry for this trouble.

Upon second thought, I suspect that using the CLI app directly is not the way to go for two reasons. First, the security implications are actually a concern as the Lift static analysis tool results suggest, especially because this function is to take user input, specifically a filename. Given that, staying away from `subprocess` seems prudent. Second, I actually do think it should be possible to call `ntia-conformance-checker` as a library still. And if there is a problem, I'll work on PRs to `ntia-conformance-checker` to make sure it can work as a library.

On the library route: I do think `sbom.print_table_output()` and `sbom.print_components_missing_info()` should both be called after instantiating [SbomChecker](https://github.com/spdx/ntia-conformance-checker/blob/c24501dc5bcca905676cbccfba20a6e78692fe58/ntia_conformance_checker/sbom_checker.py#L14). That way a user gets a table view and detailed output on any nonconformant components.

If you want to pair program at all, let me know. I'm not too skilled at actually developing an deploying web applications, so I admit to being a little turned around. Again, sorry for any trouble!

**Comment by goneall** [comment]
@jspeed-meyers - no worries - I just attempted using the SbomChecker and ran into an import problem.  I'm not really much of a Python programmer and I have to admit I spend most of my time with these import issues.

Let me know if you see an easy fix.  I'm wondering if the ntia-conformance-checker needs to export the class somehow.

The attempt is at PR #433

**Comment by jspeed-meyers** [comment]
@goneall - I come bearing good news, derived from turning ignorance into some sort of fragile, limited knowledge.

There is a fix (I think). You're right that the class needs to be exported. I put in a PR to `ntia-conformance-checker` to export the class. See [PR #434 ](https://github.com/spdx/ntia-conformance-checker/pull/83)

The code should NOW be able to be used in this manner:

```python
import ntia_conformance_checker as ntia

sbom = ntia.SbomChecker(settings.APP_DIR + uploaded_file_url)
sbom.print_table_output()
sbom.print_components_missing_info()
```

So take 3! And I'll keep debugging if there are more problems.

**Comment by goneall** [comment]
Thanks @jspeed-meyers - I think the PR is ready for review.

The output has a bit of an issue with formatting - it seems to be missing newlines, but at least it's producing output.

I'm also not sure the approach I'm using to capture the prints is the best approach.  It might be better to allow an optional parameter to the print functions in the SbomChecker so it can print directly.

Below is a screenshot of the output:

![image](https://user-images.githubusercontent.com/378172/219246193-6067a37e-8fde-45ba-b1d9-aff85cf84aa8.png)

**Comment by jspeed-meyers** [comment]
@goneall, well, it's progress :)

I opened an issue in `ntia-conformance-checker` to create a print option that is optimized ntia-conformance-checker. We can target that feature for the next release.

The crux of the problem, from a conceptual perspective, is that the current printing functionality has been optimized for a terminal, but the UI in `spdx-online-tools` doesn't appear to operate like a terminal. I suspect this won't be hard to improve, but I'll need to investigate.

I'll reviewed the PR right now too.

**Comment by goneall** [comment]
Note there is a new HTML output option: https://github.com/spdx/ntia-conformance-checker/pull/102

On the next release of the NTIA conformance checker, we can update the online tools to output HTML.
