### ISSUE TITLE
Add tests for Split View of XML Editor

### ISSUE THREAD

**Issue by techytushar** [spdx/spdx-online-tools#44]
It would be nice to have some test cases for the Split View of the XML Editor. They can be similar to the Tree Editor tests. One additional thing that can be tested is the syncing between the tree and text editors.

**Comment by anshuldutt21** [comment]
@techytushar is this issue still open because the split view editor tests are already written.

**Comment by techytushar** [comment]
Yes, the test for the split editor are already written here #86 . Thanks for asking. Closing it now!
