### ISSUE TITLE
Update Contributing.md

### ISSUE THREAD

**Issue by BassCoder2808** [spdx/spdx-online-tools#446]
I think it would be a good idea to update the `CONTRIBUTING.md` file as I think it would be a great starting point for all the new developers who wish to contribute, it can help them to familiarize themselves with the ecosystem which will be somewhat similar to [license-list-XML](https://github.com/spdx/license-list-XML/blob/main/CONTRIBUTING.md)

Would be happy to contribute to this, if the community feels it's a valid issue

**Comment by rtgdk** [comment]
@BassCoder2808 I am open to ideas. Glad if you can contribute to this.

**Comment by BassCoder2808** [comment]
Sure, I will start creating a draft then for the same

**Comment by BassCoder2808** [comment]
Hi @rtgdk I have created a basic version for the same, pls check once and let me know if anything else needs to be added to it

**Comment by rtgdk** [comment]
Looked fine to me, merged it. Thanks
