### ISSUE TITLE
Design Issue on Submit License Page

### ISSUE THREAD

**Issue by BassCoder2808** [spdx/spdx-online-tools#455]
On the page [Submit New License](https://tools.spdx.org/app/submit_new_license/), there is a patch of white space between the above toolbar and the start of the textbox as we can see in the image. This should not be there as it is a wastage of space as well as not solving anything
![image](https://user-images.githubusercontent.com/65075935/228808688-86bcbacd-3cee-46a9-a67e-bb643a805425.png)

**Comment by BassCoder2808** [comment]
Upon further inspection, the reason why this is occurring is that we have intentionally left space for the modal messages above, instead what we can do is that we will need to change the way we handle the modal messages in the `base.html` which will automatically solve this issue
![image](https://user-images.githubusercontent.com/65075935/229279045-d91484f4-599a-49cc-93a8-b5a472c808ad.png)

**Comment by BassCoder2808** [comment]
I have modified this and the new page would look something like this
![image](https://user-images.githubusercontent.com/65075935/229334375-caea4766-aeaf-48c3-81d0-3d5baa7e39d6.png)

**Comment by goneall** [comment]
Resolved with PR #459
