### ISSUE TITLE
No warning for deprecated licenses in JSON format

### ISSUE THREAD

**Issue by vargenau** [spdx/spdx-online-tools#468]
[ubuntu.spdx.json.txt](https://github.com/spdx/spdx-online-tools/files/11451245/ubuntu.spdx.json.txt)
[ubuntu.spdx.txt](https://github.com/spdx/spdx-online-tools/files/11451246/ubuntu.spdx.txt)

We have the same SBOM in tag:value format and in JSON format. Both have the same deprecated licenses, e.g. LGPL-2.1+

With the online validator https://tools.spdx.org/app/validate/ warnings are displayed for all deprecated licenses in tag:value format.

But no warnings are issued in JSON format.

I would expect to have the warnings in all formats.

**Comment by goneall** [comment]
This will be fixed with PR #465

**Comment by goneall** [comment]
Closing as this is addressed with #465
