### ISSUE TITLE
OPERATING-SYSTEM not accepted as valid Primary Package Purpose

### ISSUE THREAD

**Issue by anthonyharrison** [spdx/spdx-online-tools#475]
Analysis exception processing SPDX file: Unknown Package Purpose: OPERATING-SYSTEM 

According to clause 7.24 of SPDX 2.3. spacification, OPERATING-SYSTEM is valid

**Comment by goneall** [comment]
@anthonyharrison The JSON Schema, the value is `OPERATING_SYSTEM` with an underscore - see https://github.com/spdx/spdx-spec/blob/844144b3785dbc6a35065eda3b9d36adda874540/schemas/spdx-schema.json#L416

Note that we have a known issue in SPDX 2.3 that the JSON format isn't well specified in the text.  We've been using the JSON schema for the definitions.

Also note that we've been inconsistent in using dashes and underscores.  In many cases, we allow both and rely on the libraries to translate both forms.  In this particular case, it looks like only the underscore is supported.

We should be able to get this all cleaned up in the 3.0 release - consistency and documentation.

**Comment by goneall** [comment]
Closing this issue as it is more of a spec issue with an inconsistency between tag/value format and JSON.
