### ISSUE TITLE
password reset

### ISSUE THREAD

**Issue by UShan89** [spdx/spdx-online-tools#5]
Password reset feature would be commendable 🥇 as I love my username

**Comment by freddy28** [comment]
Hi @UShan89 
I am looking forward to working on this issue.
I can do the password reset functionality manually if you prefer that.
But I did some research and found out that [django-allauth](https://github.com/pennersr/django-allauth) could be helpful.

Please tell me what you think about it, so I know how to proceed.

**Comment by rtgdk** [comment]
@freddy28  django-allauth password reset functionality works when we use its OAuth to login through social media accounts. Here, we are currently using a simple login through Django user authentication system.

**Comment by rtgdk** [comment]
So, you can use `django.contrib.auth` to create password reset views and configure SMTP email service to send reset mails. Sending a unique one time link (an expiration to the link would be awesome but not mandatory) to reset password would be needed.

**Comment by rtgdk** [comment]
So, you can use `django.contrib.auth` to create password reset views and configure SMTP email service to send reset mails. Sending a unique one time link (an expiration to the link would be awesome but not mandatory) to reset password would be needed.

**Comment by freddy28** [comment]
@rtgdk 
Ok, THanks for the feedback. On it.
Expect a PR one of these days.

**Comment by freddy28** [comment]
@rtgdk 
I am currently working on this feature, and I would like to have an spdx source email address and password, to be used as our email service. I am currently testing this with my email address and I can't make a PR with that.

**Comment by rtgdk** [comment]
@freddy28 
You can test it locally with your credentials and in the PR leave the fields blank. 
This way anyone can test your work and also add spdx credentials in production once the PR is merged.

**Comment by freddy28** [comment]
@rtgdk 
Ok good.

**Comment by freddy28** [comment]
@pombredanne @rtgdk 
Here is the PR #11

**Comment by freddy28** [comment]
@rtgdk @pombredanne 
I have updated the #11 .
The link now has an expiration duration of 3 days:
`PASSWORD_RESET_TIMEOUT_DAYS = 3`
