### ISSUE TITLE
Missing 'removeSpecialCharacters' function

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#504]
Testing the online app, I'm now getting the following error:

```
Traceback (most recent call last): File "/spdxonlinetools/src/app/core.py", line 320, in license_validate_helper filename = fs.save(utils.removeSpecialCharacters(myfile.name), myfile) AttributeError: module 'app.utils' has no attribute 'removeSpecialCharacters'
```

From looking through the commit history, it looks like this commit caused the issue: 481ca83c20a340df29d53e1ac2d21d7045deee79

I could not find the associated pull request, so I'm not sure if there may be other issues introduced with this commit.  It looks like there was a lot of code changed in the utils file.

@BassCoder2808 @rtgdk - Could you review the commit and see if we just need to add back the function or if there may be other issues.

**Comment by rtgdk** [comment]
@goneall Looks like @BassCoder2808 removed some code in #489 in his PR and then added some of it back again in #496. Not sure why this done was done and how the PR #489 got merged. 
Took a look at all the changes - only `removeSpecialCharacters` was not added again in #496 .
@BassCoder2808 Do you know why this was done?
