### ISSUE TITLE
Missing table after updating server software

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#51]
I'm getting the following error when accessing the new license request module:

```

Request Method: | GET
-- | --
http://13.57.134.254/app/license_requests/
1.11.2
OperationalError
no such table: app_licenserequest
/home/ubuntu/.local/lib/python2.7/site-packages/django/db/models/sql/compiler.py in execute_sql, line 886
/usr/local/bin/uwsgi
2.7.12
['.',  '',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/home/ubuntu/.local/lib/python2.7/site-packages',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']
Mon, 1 Oct 2018 16:58:07 +0000
```

I ran the makemigrations and migrate django commands, but no updates were applied.

@rtgdk @gaalocastillo Let me know if you have any suggestions.

**Comment by rtgdk** [comment]
I am not facing this problem. Can you please check whether there are only two files -  `0001_initial.py` and `__init.py__` in the `src/app/migrations` folder. https://github.com/spdx/spdx-online-tools/blob/master/src/app/migrations/0001_initial.py. If not, clone the master branch with latest commit. Also, you don't have to run makemigrations command as the latest commit already contains the migrations files. Thats why no updates were applied.

**Comment by goneall** [comment]
It looks like there is an additional file 002_licensenames.py.  I'll see if I can get thing re-initialized.

**Comment by goneall** [comment]
I wasn't able to resolve the issue, but I worked around it by creating a new PostgreSQL database which is more suitable for production.

**Comment by goneall** [comment]
Since this is likely isolated to the production testing and not a general issue, I'm going to go ahead and close it.
