### ISSUE TITLE
Inconsistencies in `README-PRODUCTION.md`

### ISSUE THREAD

**Issue by BassCoder2808** [spdx/spdx-online-tools#519]
- There are minor spelling and formatting errors in `README-PRODUCTION.md`

**Comment by rtgdk** [comment]
@BassCoder2808 Please raise the fix for this or mention the exact errors for someone else to pick up. Thanks!

**Comment by goneall** [comment]
Should we also add a section to describe the runtime as documented [here](https://github.com/spdx/spdx-online-tools/pull/518#discussion_r1443869432)?

**Comment by BassCoder2808** [comment]
Sure @goneall I will add that as well in the fix and will raise the PR for the same

**Comment by goneall** [comment]
This is fixed in PR #520
