### ISSUE TITLE
Migrate to Django 2.1

### ISSUE THREAD

**Issue by rtgdk** [spdx/spdx-online-tools#58]
Similar issue #24 

Upgrade the codebase to Python 3 and Django 2.1.
Some work is already done in https://github.com/spdx/spdx-online-tools/tree/python3

**Comment by SidharajYadav** [comment]
How i can contribute
please guide me
I like to solve this problem

**Comment by autoantwort** [comment]
Can be closed. Django 3.2.15 is already used.
