### ISSUE TITLE
Debug - A global flag required to disable it

### ISSUE THREAD

**Issue by UShan89** [spdx/spdx-online-tools#6]
`api/check_license` on the online-tools hosted at https://spdxtools.sourceauditor.com/ 
is how this issue was first found. The debug is turned-on in production and a global setting to disable/enable is required

**Comment by freddy28** [comment]
@UShan89 @pombredanne 
I might be wrong, but Django already has a `debug` flag that should be changed to `False` prior to deployment.
```
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
```
If that was done, then please I would like to have more details on this issue, to take this on.

Thanks

**Comment by rtgdk** [comment]
@freddy28  Yes, this flag is already provided in Django by default in [settings.py](https://github.com/spdx/spdx-online-tools/blob/master/src/src/settings.py)

**Comment by freddy28** [comment]
@rtgdk 
Ok, 
In that case, can I have more details on the issue. I don't quite understand what the issue is about.

**Comment by UShan89** [comment]
@freddy28 having debug flag is an insecure operation for production. There are python packages and browser addons that could be leveraged for unexpected actions from an end user. 

Here is one scenario that would definitely worry me. https://pypi.python.org/pypi/django-debug-toolbar. 

If this package (say was available) then a client (Browser) can be used to make changes to almost everything.

**Comment by UShan89** [comment]
The idea is to make everything run without debug (Unless specifically asked)

**Comment by goneall** [comment]
I updated the debug flag to False on the production environment.

Propose we update the settings.py in the repo to set debug to False.  When running it on local systems during development, you can override the settings to True.  This would make it less likely we accidentally leave debug on in the production environment.
