### ISSUE TITLE
Submit new license: add question re: OSI submission

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-online-tools#66]
Can we add a question as follows:

"Have you submitted this license to the OSI or are you planning to? (if yes, use comments to explain)"
with a yes/no option for answer

**Comment by jlovejoy** [comment]
possibly could implement in exisitng question; change the question to "OSI status?" and then add in drop-down options, "approved", "not submitted", "submitted, but pending", "rejected"

**Comment by techytushar** [comment]
@goneall This can be closed as it has been fixed
