### ISSUE TITLE
Include drag and drop file method

### ISSUE THREAD

**Issue by rtgdk** [spdx/spdx-online-tools#7]
Drag and drop file method to upload would make the UX more friendly. The user should also be able to use default browse-and-select file by clicking on the drag and drop tile.

You can take inspiration from gmail's drive upload button.
![capture](https://user-images.githubusercontent.com/17159160/35776016-73067cb6-09ba-11e8-9018-eaab7ee1e0cb.PNG)

**Comment by freddy28** [comment]
@rtgdk I am on this one

**Comment by rtgdk** [comment]
@freddy28 Sure. Go ahead. 👍

**Comment by techytushar** [comment]
if anyone is not working, i would like to work on this. :blush:

**Comment by rtgdk** [comment]
@freddy28  Have started some work on it but no update in the last 12 days.
Although there is much work to be done on his PR, you can check his work out.
@techytushar  If you plan to implement this feature in any other way, you are welcome to do so.

**Comment by freddy28** [comment]
@rtgdk Please review #12 . It contains the first version to solving this issue.
