### ISSUE TITLE
Update django version

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#80]
There is a minor security vulnerability in django version 1.11.18.  We should upgrade to django ~> 1.11.18.

Note: related to issue #58

**Comment by abhishekspeer** [comment]
Hey @goneall, Can I start working on this issue?

**Comment by Ugtan** [comment]
The current verion of django is 1.11.16 so, i believe the security vulnerability is in that particular version and it should be upgraded to 1.11.18 or greater but less than 1.12. 
Also, how about considering requires.io for tracking security updates like these? @goneall
