### ISSUE TITLE
Add Python Decouple

### ISSUE THREAD

**Issue by abhishekspeer** [spdx/spdx-online-tools#85]
### Description
Python Decouple strictly separates the settings parameters from the source code. It adds parameters related to an instance of the project into a seperate .env file. All the environment-specific parameters (secret key, user, passwords, debug status and hosts to mention a few) can be kept into and changed from a single configuration module. Also, It enables changing parameters without having to redeploy the app.

Adding this into .gitignore ensures these are not pushed with the code.

The following dependency is required for this change:
`python-decouple`

**Comment by rtgdk** [comment]
Looks good. But how will it fix the need to maintain a `secret.py` file? We would still need to mention this in readme that the developer should setup up this env file to run the app.
I agree that keeping the env variable and other secret keys in a separate env file is good  and there is no harm in adding this dependency (as env file is not being committed) [Which we can make sure by not committing the secret.py 😸 ]

**Comment by rtgdk** [comment]
Resolved with #181 using `.env` files
