### ISSUE TITLE
Add a default 404 and 500 template

### ISSUE THREAD

**Issue by techytushar** [spdx/spdx-online-tools#87]
Add a basic template showing a 404 and 500 error when the user enters an invalid URL or there is some error.

**Comment by Ugtan** [comment]
I would like on this issue

**Comment by techytushar** [comment]
hey @Ugtan I appreciate your enthusiasm, but you already have 2 PRs open, I would suggest you to complete them first then pick this one up.

**Comment by bitnotri** [comment]
So the goal is to extend the basic templates we have at `app/templates/404.html` and `app/templates/500.html` ? With `Debug=False` those work, although static files need to be deployed with `collectstatic` for bootstrap to work properly.

**Comment by ithompson4** [comment]
@techytushar, @Ugtan. Could I work on this if it's still open?. Thanks.

**Comment by techytushar** [comment]
Hey @ithompson4 the error templates has been added. Thanks for your interest, please feel free to explore other open issues.
