### ISSUE TITLE
Files sent to api is saved twice

### ISSUE THREAD

**Issue by rtgdk** [spdx/spdx-online-tools#9]
In api, create model function is saving the files twice. So files sent to api is saved to 2 folders
- media/api/< username >/< time > --> (Saved by views.py)  [used by the api to call spdx java tool]
- media/apifiles/< username >/< time >  (Saved by models.py) [returned to the api user as json]

Figure out the bug and modify the code to save the file once, use that file for calling the spdx java tools function and return the path of that file.

**Comment by techytushar** [comment]
i would like to work on this :slightly_smiling_face:

**Comment by rtgdk** [comment]
Deleting the file has an overhead. It will overall slow down the API process for the user. Also, while in production it is not recommended. If you are proposing that we delete the file not when the query is going on, but once a day/week randomly at a specified time, then it can be done. But it will require the use of `crontab` or something similar. Again this will require some modification while in production. (Doable but not feasible)[Although, if you are able to come up with both feasible and easily implementable alternative to `crontab`, suggest it below]. 
The third idea of saving the file by models first is what I recommend. We are passing the file path to the JPype calling function. So, if we can get the correct file (which I think Django models support) we can use that file for both processing and returning. 
And what do you mean by 
>  but then we will not get some fields.

Elaborate.

**Comment by rtgdk** [comment]
Also while building the tool, I kept in mind about this bug. That's why I used the time field to separate similar files uploaded by the same user. So, it won't interfere with the processing issue.

**Comment by techytushar** [comment]
> but then we will not get some fields.  

If we save the file using models then we will not be able to get the `status` and the `message` field as they are generated at the end. 
Why do we need to store the file in `apifile` folder we can just store the input and result file in the `api` folder and use them.. :thinking:

**Comment by rtgdk** [comment]
> Why do we need to store the file in apifile folder we can just store the input and result file in the api folder and use them

We would need to return the result to the user. For this, how to plan to link the uploaded file from views.py to be returned to the user. (models.CharField?)
> If we save the file using models then we will not be able to get the status and the message field as they are generated at the end.

We can get the saved model data by querying and then update the status and message fields and then return to the user.

**Comment by techytushar** [comment]
this issue can be closed now :relaxed:
