### ISSUE TITLE
Add versioning information to the application

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#93]
Since we are now deploying multiple versions of the app, we should add a version to the application and display the version in the about page. It would also be nice to display the version of the SPDX tools used in the backend as well.

**Comment by rtgdk** [comment]
Totally agree with you. We should also keep track of the major changes done during the development of a version (both java and online-tools).
Ideas I can think of right now:
1. Using `settings.py` file for maintaining the current version
2. Using git tag to mark commits to a specific version and use GitHub releases feature.
3. Having a wiki where we maintain changes done in a version.
I am open to other ideas as well of tagging and maintaining version and displaying the changes in some other/third party way, if its more convenient.

**Comment by techytushar** [comment]
We can also use Milestone on GitHub to set feature requests for further versions.

**Comment by abhishekspeer** [comment]
@goneall @rtgdk @techytushar Can I work on this issue?

**Comment by rtgdk** [comment]
@abhishekspeer  Sure go ahead!

**Comment by Ugtan** [comment]
@abhishekspeer Are you still working on this issue? if not, i would like to work on it.

**Comment by abhishekspeer** [comment]
Thanks for asking @Ugtan 
I had my University exams earlier. I’m working on it right now and will submit a PR soon. Thanks again. :)

**Comment by Ugtan** [comment]
No issues 😊 @abhishekspeer

**Comment by rtgdk** [comment]
We would like to include the changelog in the wiki. (Format of the changelog should also be specified in that wiki). Before that, you should present any versioning strategy that would be best for this project. We can keep the online-tools version and java-tools version in settings.py or any other file and show it at the bottom of the web page. We should also create a wiki on how/when to change a version. Some application follow <Major.Minor.Patch> strategy. When a patch is added we change only the last digit. For eg: `1.0.1` to `1.0.2`. Also, if we can use the github release feature that would be great. Basically you can describe your strategy on the issue itself or include some PR to show how you plan to implement it. Once we have that, the mentors will help you guide what extra things can be included.

**Comment by anshuldutt21** [comment]
@rtgdk its best to include a file (versions) to show the java tools version and display the value in the web home page.

**Comment by rtgdk** [comment]
@anshuldutt21 You are welcome to open a PR for the same.
