### ISSUE TITLE
Convert mouse pointer on hover

### ISSUE THREAD

**Issue by techytushar** [spdx/spdx-online-tools#94]
On the `/app/license_requests/` and `/app/archive_requests/` page, the mouse pointer should change to finger when the user hovers over the table items (license names) so that he knows that the items are clickable. In the current version it feels like they are just for displaying the info and not clickable. There can also be some sort of highlighting on mouse hover.

**Comment by ithompson4** [comment]
Hello @techytushar. Can I work on this problem?

**Comment by techytushar** [comment]
Sure, go ahead :+1:

**Comment by ithompson4** [comment]
Hello @techytushar.
I was able to run the app and populate app_licensenames db table. But when I open `/app/license_requests/` and `/app/archive_requests/ pages`, the tables are empty. How can I populate the database tables? Thanks.

**Comment by Ugtan** [comment]
One and the easy way would be to run the command ``` python manage.py loaddata ./app/testFiles/licenseRequests.json ``` as given [here](https://github.com/spdx/spdx-online-tools/tree/master/src/app/testFiles) or else just create data in database.

**Comment by ithompson4** [comment]
Thanks, it worked.

**Comment by ithompson4** [comment]
Could you please confirm that for the clickable fields under the columns Fullname, Short Identifier, License author name, and Submission Date (UTC) the pointer should be changed to a finger when it hovers over them.
Also, that each of those clickable fields should be highlighted when hovered over.

**Comment by rtgdk** [comment]
@ithompson4 You can also use super admin Django feature to add your own licensename data rows. Also, we want that the mouse pointer should  be changed to `hand` (like when we hover over any link on google) and the hovered data row should be highlighted slight differently that the rest of the rows.

**Comment by ithompson4** [comment]
I also noticed that on the `app/archive_requests/` page when I click on the `Unarchive` button, the “Unarchive” text is underlined in red. 
Is it a potential bug? Or does it work as designed? Can I raise an issue? Thanks.

**Comment by rtgdk** [comment]
@ithompson4 I didn't notice the above bug. Can you please paste a screenshot of it?

**Comment by ithompson4** [comment]
![Screenshot](https://user-images.githubusercontent.com/16367007/54665946-dcca5500-4abe-11e9-8c55-446b499a1af0.png)

**Comment by rtgdk** [comment]
Oh okay, now I understand the problem. The Archive/unarchive button is actually <input> not <button>, that's why there's a cursor in between the text when clicked. And chrome shows red spell checker under Unarchive. @ithompson4 Can you please fix this?

**Comment by ithompson4** [comment]
Yes, Ok I will fix it.

**Comment by Ugtan** [comment]
> Oh okay, now I understand the problem. The Archive/unarchive button is actually `<input>` not `<button>`, that's why there's a cursor in between the text when clicked. And chrome shows red spell checker under Unarchive. @ithompson4 Can you please fix this?

My bad, It was not showing on my browser as i have unchecked check spellings. So, i was getting it. Sorry bout that.

> Yes, Ok I will fix it.

Please.

**Comment by techytushar** [comment]
Fixed in #102
