### ISSUE TITLE
Make the issues URL for license submittal configurable

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#95]
Currently, the URL for the license issues is hardcoded to point to the SPDX license list (https://github.com/spdx/license-list-XML/issues).  The tests are now using a test repository: https://github.com/spdx/TEST-LicenseList-XML/issues

If we could move this URL to the settings file, we could put the https://github.com/spdx/TEST-LicenseList-XML/issues URL as the default and we can replace it with the license-list-XML repo in production.

This would limit the amount of issues being generated in the license-list-XML repo while developing and testing.

**Comment by ekongobie** [comment]
Can I take this up?

**Comment by goneall** [comment]
@ekongobie yes, thanks

**Comment by ekongobie** [comment]
@goneall @pombredanne I have submitted a PR for this issue.

**Comment by goneall** [comment]
Resolved by PR #97 Thanks @ekongobie !
