### ISSUE TITLE
Change the comments field to report the comments in the issues and not include in notes

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#98]
Currently, when you submit a license, the comments are included in the notes section of the XML.

The legal team would like to include the comments in the Issues submitted to the license-list-XML repo and not include it in the `<notes> ... </notes>` section of the XML.  We'll reserve the notes section of the XML for legal team use.

**Comment by Ugtan** [comment]
@goneall So, just leave the notes in xml as empty string for now?

Also, I would like to work on this issue.

**Comment by goneall** [comment]
> So, just leave the notes in xml as empty string for now?

Yes

> Also, I would like to work on this issue.

Great - thanks!
