### ISSUE TITLE
Change default sort order for the submitted licenses to submission date

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#99]
Current default sort order is by name.  Sorting by date most recent first would be helpful in finding the most recent licenses.

**Comment by ithompson4** [comment]
Can I also fix this issue at the same time I deal with the redundant CSS for `xml_upload` and `license_information` files mentioned in the pull request #102. 
For this issues do I need to make changes inside the `/app/license_requests/` to sort by date?

**Comment by rtgdk** [comment]
@ithompson4 You can work on this one. You would have to make changes in the `views.py` function. Return the sorted data from the views to the template.

**Comment by ithompson4** [comment]
Hello, while submitting a new license, I get this error. Do I use a valid URL for this form? Thanks.Hello, while submitting a new license, I get this error. Do I use a valid URL for this form? Or is it an unhandled exception? Thanks.

![pic1](https://user-images.githubusercontent.com/16367007/55109567-8061c980-50ac-11e9-86a6-e49ed41b9fff.png)

![pic2](https://user-images.githubusercontent.com/16367007/55109611-92436c80-50ac-11e9-95da-d4bb053b1a6b.png)

**Comment by ithompson4** [comment]
I added in views.py, line 1191 `.order_by('-submissionDatetime')` but it does not sort in desc order. Am I doing anything wrong?
`licenseRequests=LicenseRequest.objects.filter(archive='False').order_by('-submissionDatetime')`

Or is it OK to add `'order': [[3, 'desc']]` in `license_requests.html`, line 57 that works sorting by date most recent license:
`<script type="text/javascript">
  $(document).ready( function () {
      $('#requests_table').DataTable({
        'info': false,
        'order': [[3, 'desc']]
      });
  });
</script>`

**Comment by rtgdk** [comment]
@ithompson4 For the first one, I think it happens when submit invalid xml. Can you raise an issue for this?

For the second one, I am surprised order_by didn't work. Can you print `licenseRequests` before returning it to the template and check whether it is in order or not? Maybe the error is due to the DataTables.

**Comment by ithompson4** [comment]
Ok, I will raise the issue concerning the exception.

Concerning `order_by` in desc order:
When I use, `licenseRequests = LicenseRequest.objects.filter(archive='False').order_by('-submissionDatetime')` to display all records in sorted in `desc`
The result - not sorted:
![order_by1](https://user-images.githubusercontent.com/16367007/55186407-dac25f00-516c-11e9-9d37-bd8b409716ac.png)

When I use `licenseRequests = LicenseRequest.objects.filter(archive='False').order_by('-submissionDatetime')[:1]` to display only the latest record (to see if order_by works)
The result: 
![order_by2](https://user-images.githubusercontent.com/16367007/55186485-0d6c5780-516d-11e9-8b8a-b479ad9d1c44.png)

**Comment by ithompson4** [comment]
So, in my template in DataTable JavaScript, I will disable sorting CSS.
